
import { MainCategory } from "./types";

export const coreCategories: MainCategory[] = [
  {
    name: "ALL AI TOOLS",
    emoji: "🌟",
    description: "Complete collection of all AI tools across every category and subcategory",
    subcategories: ["*"] // Special indicator for all tools
  },
  {
    name: "AI CHAT & ASSISTANTS",
    emoji: "🤖",
    description: "Advanced AI chatbots, virtual assistants, and conversational AI platforms for various applications",
    subcategories: [
      "AI Chat Platforms",
      "AI Assistants", 
      "Advanced Chat Platforms",
      "AI Agents",
      "Conversational AI",
      "Advanced AI Tools",
      "AI Inference Platforms",
      "AI Productivity Suite",
      "AI Productivity Tools",
      "Comprehensive AI Tools"
    ]
  },
  {
    name: "CONTENT CREATION & WRITING",
    emoji: "✍️", 
    description: "AI-powered tools for writing, content generation, copywriting, and creative writing assistance",
    subcategories: [
      // Core writing categories
      "AI Content Generators",
      "Writing & Content",
      "Content Creation Tools",
      "Writing Assistants",
      "Creative Writing Tools",
      "Grammar & Writing Assistants",
      "Content Creation & Writing Tools",
      "Writing And Content",
      "Content Creation And Writing Tools",
      "Writing And Content Enhancement",
      "Content Detection Tools",
      "AI Generative Tools",
      // Additional content categories from our database
      "Content Creation",
      "Creative Writing",
      "Writing Tools",
      "Content Generation",
      "Blog Writing",
      "Article Writing",
      "Copywriting",
      "Script Writing",
      "Book Writing",
      "Academic Writing",
      "Technical Writing",
      "Content Marketing",
      "SEO Writing",
      "Email Writing",
      "Social Media Content",
      "Newsletter Tools",
      "Content Planning",
      "Content Strategy",
      "Content Optimization",
      "Text Generation",
      "Language Tools",
      "Translation Tools",
      "Proofreading Tools",
      "Editing Tools",
      "Writing Enhancement",
      "Storytelling Tools",
      "Narrative Tools",
      "Creative Content",
      "Content Automation",
      "Content Management",
      "Publishing Tools",
      "Document Creation",
      "Presentation Tools",
      "Report Writing",
      "Proposal Writing",
      "Grant Writing",
      "Legal Writing",
      "Medical Writing",
      "Business Writing",
      "Marketing Copy",
      "Ad Copy",
      "Product Descriptions",
      "Web Content",
      "Blog Content",
      "Article Content",
      "News Writing",
      "Press Release",
      "Content Curation",
      "Content Research",
      "Fact Checking",
      "Content Analysis",
      "Writing Analytics",
      "Content Metrics",
      "Writing Productivity",
      "Writing Workflow",
      "Collaborative Writing",
      "Team Writing",
      "Writing Project Management",
      "Writing Templates",
      "Writing Prompts",
      "Creative Prompts",
      "Story Prompts",
      "Writing Inspiration",
      "Writing Ideas",
      "Content Ideas",
      "Topic Generation",
      "Headline Generation",
      "Title Generation",
      "Meta Description",
      "Content Briefs",
      "Writing Guidelines",
      "Style Guides",
      "Writing Standards",
      "Content Quality",
      "Writing Quality",
      "Content Review",
      "Writing Review",
      "Content Feedback",
      "Writing Feedback",
      "Content Collaboration",
      "Writing Collaboration",
      "Content Sharing",
      "Writing Sharing",
      "Content Publishing",
      "Writing Publishing",
      "Content Distribution",
      "Writing Distribution"
    ]
  },
  {
    name: "IMAGE & DESIGN TOOLS",
    emoji: "🎨",
    description: "AI tools for image generation, graphic design, photo editing, and visual content creation",
    subcategories: [
      "AI Art Tools",
      "AI Image Generation",
      "Image Generation Platforms",
      "Design & Graphics Tools",
      "Creative Design Tools",
      "Image & Design",
      "Image Editing Tools",
      "Specialized Image Tools",
      "Background & Object Tools",
      "Core Image Generators",
      "Design And Graphics Tools",
      "Design Assistant Tools"
    ]
  }
];
