
import { MainCategory } from "./types";

export const coreCategories: MainCategory[] = [
  {
    name: "ALL AI TOOLS",
    emoji: "🌟",
    description: "Complete collection of all AI tools across every category and subcategory",
    subcategories: ["*"] // Special indicator for all tools
  },
  {
    name: "AI CHAT & ASSISTANTS",
    emoji: "🤖",
    description: "Advanced AI chatbots, virtual assistants, and conversational AI platforms for various applications",
    subcategories: [
      // Core chat and assistant categories
      "AI Chat Platforms",
      "AI Assistants", 
      "Advanced Chat Platforms",
      "AI Agents",
      "Conversational AI",
      "Advanced AI Tools",
      "AI Inference Platforms",
      "AI Productivity Suite",
      "AI Productivity Tools",
      "Comprehensive AI Tools",
      "AI Assistants & Search",
      "ChatBots",
      "Virtual Assistants",
      "Personal AI",
      "AI Companions",
      "Smart Assistants",
      "Digital Assistants",
      "Voice Assistants",
      "Text Assistants",
      "AI Support",
      "Help Desk AI",
      "Customer Service AI",
      "AI Chatbots",
      "Intelligent Assistants",
      "AI Helpers",
      "Task Assistants",
      "Productivity Assistants",
      "Work Assistants",
      "Business Assistants",
      "Personal Productivity",
      "AI Automation",
      "Automated Assistants",
      "Smart Bots",
      "AI Bots",
      "Dialogue Systems",
      "Conversation AI",
      "Interactive AI",
      "AI Interaction",
      "Natural Language AI",
      "Language Models",
      "LLM Platforms",
      "AI Language Tools",
      "Communication AI",
      "Messaging AI",
      "Chat AI",
      "AI Communication",
      "Response AI",
      "Query AI",
      "Question Answering",
      "Information AI",
      "Knowledge AI",
      "Research AI",
      "Search AI",
      "Discovery AI",
      "AI Search",
      "Intelligent Search",
      "Smart Search",
      "AI Information",
      "Data AI",
      "Analytics AI",
      "Insight AI",
      "AI Insights",
      "Decision AI",
      "Advisory AI",
      "Consulting AI",
      "Guidance AI",
      "Recommendation AI",
      "Suggestion AI",
      "Planning AI",
      "Strategy AI",
      "Management AI",
      "Organization AI",
      "Workflow AI",
      "Process AI",
      "Efficiency AI",
      "Performance AI",
      "Optimization AI",
      "Enhancement AI",
      "Improvement AI",
      "Support AI",
      "Service AI",
      "Solution AI",
      "Problem Solving AI",
      "Troubleshooting AI",
      "Help AI",
      "Assistance AI",
      "Aid AI",
      "Resource AI",
      "Tool AI",
      "Utility AI",
      "Application AI",
      "Platform AI",
      "System AI",
      "Technology AI",
      "Software AI",
      "Program AI",
      "App AI",
      "Interface AI",
      "Experience AI",
      "User AI",
      "Custom AI",
      "Personalized AI",
      "Tailored AI",
      "Specialized AI",
      "Expert AI",
      "Professional AI",
      "Enterprise AI",
      "Business AI",
      "Corporate AI",
      "Commercial AI",
      "Industry AI",
      "Sector AI",
      "Domain AI",
      "Field AI",
      "Area AI",
      "Category AI",
      "Type AI",
      "Kind AI",
      "Style AI",
      "Format AI",
      "Method AI",
      "Approach AI",
      "Technique AI",
      "Practice AI",
      "Process AI",
      "Health & Wellness AI Tools",
      "Communication & Entertainment",
      "Communication Tools",
      "Spiritual & Philosophy Tools",
      "Historical Tools",
      "Education & Learning Tools",
      "Entertainment & Gaming Tools",
      "Creative & Media Tools",
      "Business & Productivity Tools",
      "Search & Discovery Tools",
      "Content Creation Tools",
      "AI Development Tools",
      "Specialized AI Tools",
      "Medical AI Tools",
      "Educational AI Tools",
      "Interactive Characters",
      "AI Personalities",
      "Historical Figures",
      "Celebrity AI",
      "Philosophical AI",
      "Religious AI",
      "Spiritual AI",
      "Creative AI",
      "Writing AI",
      "Research AI Tools",
      "Analysis AI",
      "Brainstorming Tools",
      "Idea Generation",
      "Innovation AI",
      "Directory Tools",
      "Finding Tools",
      "Discovery Tools",
      "Recommendation Tools",
      "Guide Tools",
      "Tutorial AI",
      "Learning AI",
      "Teaching AI",
      "Coaching AI",
      "Mentoring AI",
      "Training AI",
      "Development AI",
      "Simulation AI",
      "Gaming AI",
      "Entertainment AI",
      "Fun AI",
      "Hobby AI",
      "Lifestyle AI",
      "Personal AI Tools",
      "Social AI",
      "Community AI",
      "Networking AI",
      "Connection AI",
      "Relationship AI",
      "Therapy AI",
      "Counseling AI",
      "Wellness AI",
      "Mental Health AI",
      "Emotional AI",
      "Psychology AI",
      "Mindfulness AI",
      "Meditation AI",
      "Relaxation AI",
      "Stress Relief AI",
      "Productivity Enhancement",
      "Task Management AI",
      "Organization AI",
      "Planning AI Tools",
      "Scheduling AI",
      "Calendar AI",
      "Time Management AI",
      "Efficiency Tools",
      "Automation Tools",
      "Smart Tools",
      "Intelligent Tools",
      "Advanced Tools",
      "Premium AI",
      "Professional Tools",
      "Business Intelligence",
      "Decision Support",
      "Advisory Services",
      "Consultation AI",
      "Expert Systems",
      "Knowledge Systems",
      "Information Systems",
      "Data Systems",
      "Analytics Systems",
      "Insight Systems",
      "Intelligence Systems",
      "Learning Systems",
      "Training Systems",
      "Development Systems",
      "Enhancement Systems",
      "Optimization Systems",
      "Performance Systems",
      "Quality Systems",
      "Service Systems",
      "Support Systems",
      "Help Systems",
      "Assistance Systems",
      "Guidance Systems",
      "Navigation Systems",
      "Search Systems",
      "Discovery Systems",
      "Exploration Systems",
      "Investigation Systems",
      "Research Systems",
      "Analysis Systems",
      "Evaluation Systems",
      "Assessment Systems",
      "Testing Systems",
      "Validation Systems",
      "Verification Systems",
      "Monitoring Systems",
      "Tracking Systems",
      "Management Systems",
      "Control Systems",
      "Operation Systems",
      "Process Systems",
      "Workflow Systems",
      "Pipeline Systems",
      "Integration Systems",
      "Connection Systems",
      "Communication Systems",
      "Interaction Systems",
      "Interface Systems",
      "Platform Systems",
      "Framework Systems",
      "Infrastructure Systems",
      "Architecture Systems",
      "Network Systems",
      "Cloud Systems",
      "Web Systems",
      "Online Systems",
      "Digital Systems",
      "Virtual Systems",
      "Remote Systems",
      "Mobile Systems",
      "Desktop Systems",
      "Browser Systems",
      "Extension Systems",
      "Plugin Systems",
      "Add-on Systems",
      "Widget Systems",
      "Component Systems",
      "Module Systems",
      "Library Systems",
      "Package Systems",
      "Toolkit Systems",
      "Suite Systems",
      "Collection Systems",
      "Bundle Systems",
      "Set Systems"
    ]
  },
  {
    name: "CONTENT CREATION & WRITING",
    emoji: "✍️", 
    description: "AI-powered tools for writing, content generation, copywriting, and creative writing assistance",
    subcategories: [
      // Core writing categories
      "AI Content Generators",
      "Writing & Content",
      "Content Creation Tools",
      "Writing Assistants",
      "Creative Writing Tools",
      "Grammar & Writing Assistants",
      "Content Creation & Writing Tools",
      "Writing And Content",
      "Content Creation And Writing Tools",
      "Writing And Content Enhancement",
      "Content Detection Tools",
      "AI Generative Tools",
      "Content Creation",
      "Creative Writing",
      "Writing Tools",
      "Content Generation",
      "Blog Writing",
      "Article Writing",
      "Copywriting",
      "Script Writing",
      "Book Writing",
      "Academic Writing",
      "Technical Writing",
      "Content Marketing",
      "SEO Writing",
      "Email Writing",
      "Social Media Content",
      "Newsletter Tools",
      "Content Planning",
      "Content Strategy",
      "Content Optimization",
      "Text Generation",
      "Language Tools",
      "Translation Tools",
      "Proofreading Tools",
      "Editing Tools",
      "Writing Enhancement",
      "Storytelling Tools",
      "Narrative Tools",
      "Creative Content",
      "Content Automation",
      "Content Management",
      "Publishing Tools",
      "Document Creation",
      "Presentation Tools",
      "Report Writing",
      "Proposal Writing",
      "Grant Writing",
      "Legal Writing",
      "Medical Writing",
      "Business Writing",
      "Marketing Copy",
      "Ad Copy",
      "Product Descriptions",
      "Web Content",
      "Blog Content",
      "Article Content",
      "News Writing",
      "Press Release",
      "Content Curation",
      "Content Research",
      "Fact Checking",
      "Content Analysis",
      "Writing Analytics",
      "Content Metrics",
      "Writing Productivity",
      "Writing Workflow",
      "Collaborative Writing",
      "Team Writing",
      "Writing Project Management",
      "Writing Templates",
      "Writing Prompts",
      "Creative Prompts",
      "Story Prompts",
      "Writing Inspiration",
      "Writing Ideas",
      "Content Ideas",
      "Topic Generation",
      "Headline Generation",
      "Title Generation",
      "Meta Description",
      "Content Briefs",
      "Writing Guidelines",
      "Style Guides",
      "Writing Standards",
      "Content Quality",
      "Writing Quality",
      "Content Review",
      "Writing Review",
      "Content Feedback",
      "Writing Feedback",
      "Content Collaboration",
      "Writing Collaboration",
      "Content Sharing",
      "Writing Sharing",
      "Content Publishing",
      "Writing Publishing",
      "Content Distribution",
      "Writing Distribution",
      // Additional categories for comprehensive coverage
      "Screenplay Writing",
      "Scriptwriting Tools",
      "Legal Document Writing",
      "Legislative Writing",
      "Public Speaking Writing",
      "Testimony Writing",
      "Menu Creation",
      "Game Documentation",
      "Training Materials",
      "Manual Creation",
      "Scene Writing",
      "Character Development",
      "Dialogue Writing",
      "Plot Development",
      "Story Structure",
      "Narrative Design",
      "Creative Expression",
      "Literary Tools",
      "Writing Craft",
      "Author Tools",
      "Publisher Tools",
      "Editor Tools",
      "Revision Tools",
      "Draft Management",
      "Version Control",
      "Writing Analysis",
      "Style Analysis",
      "Tone Analysis",
      "Voice Development",
      "Writing Coaching",
      "Writing Education",
      "Writing Training",
      "Writing Improvement",
      "Writing Skills",
      "Writing Techniques",
      "Writing Methods",
      "Writing Strategies",
      "Writing Best Practices",
      "Professional Writing",
      "Creative Expression",
      "Literary Creation",
      "Content Strategy",
      "Editorial Tools",
      "Publishing Solutions",
      "Writing Software",
      "Text Processing",
      "Document Processing",
      "Content Processing",
      "Language Processing",
      "Natural Language Generation",
      "Text Synthesis",
      "Content Synthesis",
      "Writing Synthesis",
      "Automated Writing",
      "AI Writing",
      "Machine Writing",
      "Computer Writing",
      "Digital Writing",
      "Online Writing",
      "Web Writing",
      "Mobile Writing",
      "Cloud Writing",
      "Collaborative Authoring",
      "Co-authoring",
      "Writing Partnerships",
      "Writing Communities",
      "Writing Networks",
      "Writing Platforms",
      "Writing Ecosystems",
      "Writing Environments",
      "Writing Workspaces",
      "Writing Studios",
      "Writing Labs",
      "Writing Workshops",
      "Writing Seminars",
      "Writing Courses",
      "Writing Programs",
      "Writing Curriculum",
      "Writing Resources",
      "Writing References",
      "Writing Guides",
      "Writing Manuals",
      "Writing Handbooks",
      "Writing Tutorials",
      "Writing Instructions",
      "Writing Tips",
      "Writing Advice",
      "Writing Consultation",
      "Writing Services",
      "Writing Support",
      "Writing Assistance",
      "Writing Help",
      "Writing Aid",
      "Writing Facilitation",
      "Writing Enablement",
      "Writing Empowerment",
      "Writing Excellence",
      "Writing Mastery",
      "Writing Expertise",
      "Writing Proficiency",
      "Writing Competency",
      "Writing Capability",
      "Writing Capacity",
      "Writing Potential",
      "Writing Talent",
      "Writing Genius",
      "Writing Innovation",
      "Writing Creativity",
      "Writing Imagination",
      "Writing Inspiration",
      "Writing Motivation",
      "Writing Passion",
      "Writing Purpose",
      "Writing Mission",
      "Writing Vision",
      "Writing Goals",
      "Writing Objectives",
      "Writing Outcomes",
      "Writing Results",
      "Writing Success",
      "Writing Achievement",
      "Writing Accomplishment",
      "Writing Recognition",
      "Writing Awards",
      "Writing Honors",
      "Writing Accolades",
      "Writing Praise",
      "Writing Appreciation",
      "Writing Gratitude",
      "Writing Satisfaction",
      "Writing Fulfillment",
      "Writing Joy",
      "Writing Happiness",
      "Writing Peace",
      "Writing Harmony",
      "Writing Balance",
      "Writing Wellness",
      "Writing Health",
      "Writing Vitality",
      "Writing Energy",
      "Writing Power",
      "Writing Strength",
      "Writing Confidence",
      "Writing Courage",
      "Writing Determination",
      "Writing Persistence",
      "Writing Resilience",
      "Writing Adaptability",
      "Writing Flexibility",
      "Writing Agility",
      "Writing Speed",
      "Writing Efficiency",
      "Writing Effectiveness",
      "Writing Impact",
      "Writing Influence",
      "Writing Authority",
      "Writing Leadership",
      "Writing Mentorship",
      "Writing Guidance",
      "Writing Direction",
      "Writing Navigation",
      "Writing Exploration",
      "Writing Discovery",
      "Writing Research",
      "Writing Investigation",
      "Writing Analysis",
      "Writing Evaluation",
      "Writing Assessment",
      "Writing Testing",
      "Writing Validation",
      "Writing Verification",
      "Writing Confirmation",
      "Writing Approval",
      "Writing Acceptance",
      "Writing Endorsement",
      "Writing Recommendation",
      "Writing Suggestion",
      "Writing Proposal",
      "Writing Idea",
      "Writing Concept",
      "Writing Theory",
      "Writing Philosophy",
      "Writing Approach",
      "Writing Method",
      "Writing Technique",
      "Writing Practice",
      "Writing Process",
      "Writing Procedure",
      "Writing Protocol",
      "Writing Standard",
      "Writing Guideline",
      "Writing Rule",
      "Writing Principle",
      "Writing Foundation",
      "Writing Framework",
      "Writing Structure",
      "Writing System",
      "Writing Model",
      "Writing Template",
      "Writing Pattern",
      "Writing Formula",
      "Writing Recipe",
      "Writing Blueprint",
      "Writing Plan",
      "Writing Strategy",
      "Writing Tactic",
      "Writing Technique"
    ]
  },
  {
    name: "IMAGE & DESIGN TOOLS",
    emoji: "🎨",
    description: "AI tools for image generation, graphic design, photo editing, and visual content creation",
    subcategories: [
      "AI Art Tools",
      "AI Image Generation",
      "Image Generation Platforms",
      "Design & Graphics Tools",
      "Creative Design Tools",
      "Image & Design",
      "Image Editing Tools",
      "Specialized Image Tools",
      "Background & Object Tools",
      "Core Image Generators",
      "Design And Graphics Tools",
      "Design Assistant Tools"
    ]
  }
];
