
import { MainCategory } from "./types";

export const coreCategories: MainCategory[] = [
  {
    name: "ALL AI TOOLS",
    emoji: "🌟",
    description: "Complete collection of all AI tools across every category and subcategory",
    subcategories: ["*"] // Special indicator for all tools
  },
  {
    name: "AI CHAT & ASSISTANTS",
    emoji: "🤖",
    description: "Advanced AI chatbots, virtual assistants, and conversational AI platforms for various applications",
    subcategories: [
      // Core chat and assistant categories
      "AI Chat Platforms",
      "AI Assistants", 
      "Advanced Chat Platforms",
      "AI Agents",
      "Conversational AI",
      "Advanced AI Tools",
      "AI Inference Platforms",
      "AI Productivity Suite",
      "AI Productivity Tools",
      "Comprehensive AI Tools",
      "AI Assistants & Search",
      "ChatBots",
      "Virtual Assistants",
      "Personal AI",
      "AI Companions",
      "Smart Assistants",
      "Digital Assistants",
      "Voice Assistants",
      "Text Assistants",
      "AI Support",
      "Help Desk AI",
      "Customer Service AI",
      "AI Chatbots",
      "Intelligent Assistants",
      "AI Helpers",
      "Task Assistants",
      "Productivity Assistants",
      "Work Assistants",
      "Business Assistants",
      "Personal Productivity",
      "AI Automation",
      "Automated Assistants",
      "Smart Bots",
      "AI Bots",
      "Dialogue Systems",
      "Conversation AI",
      "Interactive AI",
      "AI Interaction",
      "Natural Language AI",
      "Language Models",
      "LLM Platforms",
      "AI Language Tools",
      "Communication AI",
      "Messaging AI",
      "Chat AI",
      "AI Communication",
      "Response AI",
      "Query AI",
      "Question Answering",
      "Information AI",
      "Knowledge AI",
      "Research AI",
      "Search AI",
      "Discovery AI",
      "AI Search",
      "Intelligent Search",
      "Smart Search",
      "AI Information",
      "Data AI",
      "Analytics AI",
      "Insight AI",
      "AI Insights",
      "Decision AI",
      "Advisory AI",
      "Consulting AI",
      "Guidance AI",
      "Recommendation AI",
      "Suggestion AI",
      "Planning AI",
      "Strategy AI",
      "Management AI",
      "Organization AI",
      "Workflow AI",
      "Process AI",
      "Efficiency AI",
      "Performance AI",
      "Optimization AI",
      "Enhancement AI",
      "Improvement AI",
      "Support AI",
      "Service AI",
      "Solution AI",
      "Problem Solving AI",
      "Troubleshooting AI",
      "Help AI",
      "Assistance AI",
      "Aid AI",
      "Resource AI",
      "Tool AI",
      "Utility AI",
      "Application AI",
      "Platform AI",
      "System AI",
      "Technology AI",
      "Software AI",
      "Program AI",
      "App AI",
      "Interface AI",
      "Experience AI",
      "User AI",
      "Custom AI",
      "Personalized AI",
      "Tailored AI",
      "Specialized AI",
      "Expert AI",
      "Professional AI",
      "Enterprise AI",
      "Business AI",
      "Corporate AI",
      "Commercial AI",
      "Industry AI",
      "Sector AI",
      "Domain AI",
      "Field AI",
      "Area AI",
      "Category AI",
      "Type AI",
      "Kind AI",
      "Style AI",
      "Format AI",
      "Method AI",
      "Approach AI",
      "Technique AI",
      "Practice AI",
      "Process AI",
      "Health & Wellness AI Tools",
      "Communication & Entertainment",
      "Communication Tools",
      "Spiritual & Philosophy Tools",
      "Historical Tools",
      "Education & Learning Tools",
      "Entertainment & Gaming Tools",
      "Creative & Media Tools",
      "Business & Productivity Tools",
      "Search & Discovery Tools",
      "Content Creation Tools",
      "AI Development Tools",
      "Specialized AI Tools",
      "Medical AI Tools",
      "Educational AI Tools",
      "Interactive Characters",
      "AI Personalities",
      "Historical Figures",
      "Celebrity AI",
      "Philosophical AI",
      "Religious AI",
      "Spiritual AI",
      "Creative AI",
      "Writing AI",
      "Research AI Tools",
      "Analysis AI",
      "Brainstorming Tools",
      "Idea Generation",
      "Innovation AI",
      "Directory Tools",
      "Finding Tools",
      "Discovery Tools",
      "Recommendation Tools",
      "Guide Tools",
      "Tutorial AI",
      "Learning AI",
      "Teaching AI",
      "Coaching AI",
      "Mentoring AI",
      "Training AI",
      "Development AI",
      "Simulation AI",
      "Gaming AI",
      "Entertainment AI",
      "Fun AI",
      "Hobby AI",
      "Lifestyle AI",
      "Personal AI Tools",
      "Social AI",
      "Community AI",
      "Networking AI",
      "Connection AI",
      "Relationship AI",
      "Therapy AI",
      "Counseling AI",
      "Wellness AI",
      "Mental Health AI",
      "Emotional AI",
      "Psychology AI",
      "Mindfulness AI",
      "Meditation AI",
      "Relaxation AI",
      "Stress Relief AI",
      "Productivity Enhancement",
      "Task Management AI",
      "Organization AI",
      "Planning AI Tools",
      "Scheduling AI",
      "Calendar AI",
      "Time Management AI",
      "Efficiency Tools",
      "Automation Tools",
      "Smart Tools",
      "Intelligent Tools",
      "Advanced Tools",
      "Premium AI",
      "Professional Tools",
      "Business Intelligence",
      "Decision Support",
      "Advisory Services",
      "Consultation AI",
      "Expert Systems",
      "Knowledge Systems",
      "Information Systems",
      "Data Systems",
      "Analytics Systems",
      "Insight Systems",
      "Intelligence Systems",
      "Learning Systems",
      "Training Systems",
      "Development Systems",
      "Enhancement Systems",
      "Optimization Systems",
      "Performance Systems",
      "Quality Systems",
      "Service Systems",
      "Support Systems",
      "Help Systems",
      "Assistance Systems",
      "Guidance Systems",
      "Navigation Systems",
      "Search Systems",
      "Discovery Systems",
      "Exploration Systems",
      "Investigation Systems",
      "Research Systems",
      "Analysis Systems",
      "Evaluation Systems",
      "Assessment Systems",
      "Testing Systems",
      "Validation Systems",
      "Verification Systems",
      "Monitoring Systems",
      "Tracking Systems",
      "Management Systems",
      "Control Systems",
      "Operation Systems",
      "Process Systems",
      "Workflow Systems",
      "Pipeline Systems",
      "Integration Systems",
      "Connection Systems",
      "Communication Systems",
      "Interaction Systems",
      "Interface Systems",
      "Platform Systems",
      "Framework Systems",
      "Infrastructure Systems",
      "Architecture Systems",
      "Network Systems",
      "Cloud Systems",
      "Web Systems",
      "Online Systems",
      "Digital Systems",
      "Virtual Systems",
      "Remote Systems",
      "Mobile Systems",
      "Desktop Systems",
      "Browser Systems",
      "Extension Systems",
      "Plugin Systems",
      "Add-on Systems",
      "Widget Systems",
      "Component Systems",
      "Module Systems",
      "Library Systems",
      "Package Systems",
      "Toolkit Systems",
      "Suite Systems",
      "Collection Systems",
      "Bundle Systems",
      "Set Systems"
    ]
  },
  {
    name: "CONTENT CREATION & WRITING",
    emoji: "✍️", 
    description: "AI-powered tools for writing, content generation, copywriting, and creative writing assistance",
    subcategories: [
      // Core writing categories
      "AI Content Generators",
      "Writing & Content",
      "Content Creation Tools",
      "Writing Assistants",
      "Creative Writing Tools",
      "Grammar & Writing Assistants",
      "Content Creation & Writing Tools",
      "Writing And Content",
      "Content Creation And Writing Tools",
      "Writing And Content Enhancement",
      "Content Detection Tools",
      "AI Generative Tools",
      "Content Creation",
      "Creative Writing",
      "Writing Tools",
      "Content Generation",
      "Blog Writing",
      "Article Writing",
      "Copywriting",
      "Script Writing",
      "Book Writing",
      "Academic Writing",
      "Technical Writing",
      "Content Marketing",
      "SEO Writing",
      "Email Writing",
      "Social Media Content",
      "Newsletter Tools",
      "Content Planning",
      "Content Strategy",
      "Content Optimization",
      "Text Generation",
      "Language Tools",
      "Translation Tools",
      "Proofreading Tools",
      "Editing Tools",
      "Writing Enhancement",
      "Storytelling Tools",
      "Narrative Tools",
      "Creative Content",
      "Content Automation",
      "Content Management",
      "Publishing Tools",
      "Document Creation",
      "Presentation Tools",
      "Report Writing",
      "Proposal Writing",
      "Grant Writing",
      "Legal Writing",
      "Medical Writing",
      "Business Writing",
      "Marketing Copy",
      "Ad Copy",
      "Product Descriptions",
      "Web Content",
      "Blog Content",
      "Article Content",
      "News Writing",
      "Press Release",
      "Content Curation",
      "Content Research",
      "Fact Checking",
      "Content Analysis",
      "Writing Analytics",
      "Content Metrics",
      "Writing Productivity",
      "Writing Workflow",
      "Collaborative Writing",
      "Team Writing",
      "Writing Project Management",
      "Writing Templates",
      "Writing Prompts",
      "Creative Prompts",
      "Story Prompts",
      "Writing Inspiration",
      "Writing Ideas",
      "Content Ideas",
      "Topic Generation",
      "Headline Generation",
      "Title Generation",
      "Meta Description",
      "Content Briefs",
      "Writing Guidelines",
      "Style Guides",
      "Writing Standards",
      "Content Quality",
      "Writing Quality",
      "Content Review",
      "Writing Review",
      "Content Feedback",
      "Writing Feedback",
      "Content Collaboration",
      "Writing Collaboration",
      "Content Sharing",
      "Writing Sharing",
      "Content Publishing",
      "Writing Publishing",
      "Content Distribution",
      "Writing Distribution",
      "Screenplay Writing",
      "Scriptwriting Tools",
      "Legal Document Writing",
      "Legislative Writing",
      "Public Speaking Writing",
      "Testimony Writing",
      "Menu Creation",
      "Game Documentation",
      "Training Materials",
      "Manual Creation",
      "Scene Writing",
      "Character Development",
      "Dialogue Writing",
      "Plot Development",
      "Story Structure",
      "Narrative Design",
      "Creative Expression",
      "Literary Tools",
      "Writing Craft",
      "Author Tools",
      "Publisher Tools",
      "Editor Tools",
      "Revision Tools",
      "Draft Management",
      "Version Control",
      "Writing Analysis",
      "Style Analysis",
      "Tone Analysis",
      "Voice Development",
      "Writing Coaching",
      "Writing Education",
      "Writing Training",
      "Writing Improvement",
      "Writing Skills",
      "Writing Techniques",
      "Writing Methods",
      "Writing Strategies",
      "Writing Best Practices",
      "Professional Writing",
      "Creative Expression",
      "Literary Creation",
      "Content Strategy",
      "Editorial Tools",
      "Publishing Solutions",
      "Writing Software",
      "Text Processing",
      "Document Processing",
      "Content Processing",
      "Language Processing",
      "Natural Language Generation",
      "Text Synthesis",
      "Content Synthesis",
      "Writing Synthesis",
      "Automated Writing",
      "AI Writing",
      "Machine Writing",
      "Computer Writing",
      "Digital Writing",
      "Online Writing",
      "Web Writing",
      "Mobile Writing",
      "Cloud Writing",
      "Collaborative Authoring",
      "Co-authoring",
      "Writing Partnerships",
      "Writing Communities",
      "Writing Networks",
      "Writing Platforms",
      "Writing Ecosystems",
      "Writing Environments",
      "Writing Workspaces",
      "Writing Studios",
      "Writing Labs",
      "Writing Workshops",
      "Writing Seminars",
      "Writing Courses",
      "Writing Programs",
      "Writing Curriculum",
      "Writing Resources",
      "Writing References",
      "Writing Guides",
      "Writing Manuals",
      "Writing Handbooks",
      "Writing Tutorials",
      "Writing Instructions",
      "Writing Tips",
      "Writing Advice",
      "Writing Consultation",
      "Writing Services",
      "Writing Support",
      "Writing Assistance",
      "Writing Help",
      "Writing Aid",
      "Writing Facilitation",
      "Writing Enablement",
      "Writing Empowerment",
      "Writing Excellence",
      "Writing Mastery",
      "Writing Expertise",
      "Writing Proficiency",
      "Writing Competency",
      "Writing Capability",
      "Writing Capacity",
      "Writing Potential",
      "Writing Talent",
      "Writing Genius",
      "Writing Innovation",
      "Writing Creativity",
      "Writing Imagination",
      "Writing Inspiration",
      "Writing Motivation",
      "Writing Passion",
      "Writing Purpose",
      "Writing Mission",
      "Writing Vision",
      "Writing Goals",
      "Writing Objectives",
      "Writing Outcomes",
      "Writing Results",
      "Writing Success",
      "Writing Achievement",
      "Writing Accomplishment",
      "Writing Recognition",
      "Writing Awards",
      "Writing Honors",
      "Writing Accolades",
      "Writing Praise",
      "Writing Appreciation",
      "Writing Gratitude",
      "Writing Satisfaction",
      "Writing Fulfillment",
      "Writing Joy",
      "Writing Happiness",
      "Writing Peace",
      "Writing Harmony",
      "Writing Balance",
      "Writing Wellness",
      "Writing Health",
      "Writing Vitality",
      "Writing Energy",
      "Writing Power",
      "Writing Strength",
      "Writing Confidence",
      "Writing Courage",
      "Writing Determination",
      "Writing Persistence",
      "Writing Resilience",
      "Writing Adaptability",
      "Writing Flexibility",
      "Writing Agility",
      "Writing Speed",
      "Writing Efficiency",
      "Writing Effectiveness",
      "Writing Impact",
      "Writing Influence",
      "Writing Authority",
      "Writing Leadership",
      "Writing Mentorship",
      "Writing Guidance",
      "Writing Direction",
      "Writing Navigation",
      "Writing Exploration",
      "Writing Discovery",
      "Writing Research",
      "Writing Investigation",
      "Writing Analysis",
      "Writing Evaluation",
      "Writing Assessment",
      "Writing Testing",
      "Writing Validation",
      "Writing Verification",
      "Writing Confirmation",
      "Writing Approval",
      "Writing Acceptance",
      "Writing Endorsement",
      "Writing Recommendation",
      "Writing Suggestion",
      "Writing Proposal",
      "Writing Idea",
      "Writing Concept",
      "Writing Theory",
      "Writing Philosophy",
      "Writing Approach",
      "Writing Method",
      "Writing Technique",
      "Writing Practice",
      "Writing Process",
      "Writing Procedure",
      "Writing Protocol",
      "Writing Standard",
      "Writing Guideline",
      "Writing Rule",
      "Writing Principle",
      "Writing Foundation",
      "Writing Framework",
      "Writing Structure",
      "Writing System",
      "Writing Model",
      "Writing Template",
      "Writing Pattern",
      "Writing Formula",
      "Writing Recipe",
      "Writing Blueprint",
      "Writing Plan",
      "Writing Strategy",
      "Writing Tactic",
      "Writing Technique"
    ]
  },
  {
    name: "IMAGE & DESIGN TOOLS",
    emoji: "🎨",
    description: "AI tools for image generation, graphic design, photo editing, and visual content creation",
    subcategories: [
      // Core Image Generation & AI Art
      "AI Art Tools",
      "AI Image Generation",
      "Image Generation Platforms",
      "Core Image Generators",
      "AI Art Generation",
      "Generative AI Art",
      "AI Visual Creation",
      "AI Art Platforms",
      "Digital Art AI",
      "Creative AI Art",
      "Art Generation Tools",
      "Visual AI Tools",
      "AI Illustration",
      "AI Drawing",
      "AI Painting",
      "AI Sketch",
      "AI Creative Tools",
      "AI Visual Design",
      "AI Artistic Tools",
      "AI Image Creator",
      "AI Picture Generator",
      "AI Visual Generator",
      "AI Art Creator",
      "AI Design Generator",
      "AI Graphics Generator",
      "AI Visual Content",
      "AI Art Studio",
      "AI Creative Studio",
      "AI Design Studio",
      "AI Visual Studio",
      
      // Design & Graphics
      "Design & Graphics Tools",
      "Creative Design Tools",
      "Graphic Design Tools",
      "Visual Design Tools",
      "Design Assistant Tools",
      "Professional Design",
      "Graphic Design AI",
      "Logo Design",
      "Brand Design",
      "Identity Design",
      "Marketing Design",
      "Print Design",
      "Digital Design",
      "Web Design Graphics",
      "UI Graphics",
      "UX Graphics",
      "Design Templates",
      "Design Assets",
      "Design Resources",
      "Design Elements",
      "Design Components",
      "Design Systems",
      "Design Workflows",
      "Design Automation",
      "Design Enhancement",
      "Design Optimization",
      "Design Creation",
      "Design Generation",
      "Design Innovation",
      "Design Solutions",
      "Design Platforms",
      "Design Software",
      "Design Applications",
      "Design Tools",
      "Design Utilities",
      "Design Services",
      "Design Support",
      "Design Assistance",
      
      // Image Editing & Enhancement
      "Image & Design",
      "Image Editing Tools",
      "Photo Editing",
      "Image Enhancement",
      "Image Processing",
      "Image Manipulation",
      "Image Optimization",
      "Image Restoration",
      "Image Repair",
      "Image Upscaling",
      "Image Colorization",
      "Image Filtering",
      "Image Effects",
      "Image Transformation",
      "Image Conversion",
      "Image Compression",
      "Image Quality",
      "Image Resolution",
      "Image Clarity",
      "Image Sharpening",
      "Image Denoising",
      "Image Cleanup",
      "Image Retouching",
      "Image Correction",
      "Image Adjustment",
      "Image Modification",
      "Image Editing Software",
      "Image Editing Applications",
      "Image Editing Platforms",
      "Image Editing Services",
      "Image Editing Tools",
      "Image Editing AI",
      "AI Image Editing",
      "AI Photo Editing",
      "AI Image Enhancement",
      "AI Image Processing",
      
      // Specialized Image Tools
      "Specialized Image Tools",
      "Background & Object Tools",
      "Background Removal",
      "Object Removal",
      "Watermark Removal",
      "Image Background",
      "Image Objects",
      "Image Segmentation",
      "Image Masking",
      "Image Cropping",
      "Image Resizing",
      "Image Formatting",
      "Image Conversion Tools",
      "Image Format Tools",
      "Image Export Tools",
      "Image Import Tools",
      "Image Transfer Tools",
      "Image Sharing Tools",
      "Image Storage Tools",
      "Image Management",
      "Image Organization",
      "Image Cataloging",
      "Image Tagging",
      "Image Search",
      "Image Discovery",
      "Image Library",
      "Image Gallery",
      "Image Portfolio",
      "Image Collection",
      "Image Archive",
      "Image Database",
      
      // Creative & Artistic Tools
      "Creative & Media Tools",
      "Creative & Media",
      "Multimedia & Content",
      "Creative Tools",
      "Artistic Tools",
      "Art Tools",
      "Drawing Tools",
      "Painting Tools",
      "Illustration Tools",
      "Sketch Tools",
      "Digital Art Tools",
      "Creative Software",
      "Art Software",
      "Design Software",
      "Creative Applications",
      "Art Applications",
      "Design Applications",
      "Creative Platforms",
      "Art Platforms",
      "Design Platforms",
      "Creative Services",
      "Art Services",
      "Design Services",
      "Creative Solutions",
      "Art Solutions",
      "Design Solutions",
      
      // Specific Tool Categories
      "Color Tools",
      "Color Palette Tools",
      "Color Generation",
      "Color Matching",
      "Color Theory",
      "Color Harmony",
      "Color Schemes",
      "Color Combinations",
      "Typography Tools",
      "Font Tools",
      "Text Design",
      "Lettering Tools",
      "Type Design",
      "Font Generation",
      "Text Effects",
      "Text Styling",
      "Layout Tools",
      "Composition Tools",
      "Grid Tools",
      "Alignment Tools",
      "Spacing Tools",
      "Margin Tools",
      "Padding Tools",
      "Structure Tools",
      "Framework Tools",
      "Template Tools",
      "Pattern Tools",
      "Texture Tools",
      "Shape Tools",
      "Vector Tools",
      "Illustration Generation",
      "Icon Tools",
      "Symbol Tools",
      "Badge Tools",
      "Logo Generation",
      "Brand Tools",
      "Identity Tools",
      "Branding Tools",
      "Marketing Graphics",
      "Social Media Graphics",
      "Web Graphics",
      "Print Graphics",
      "Presentation Graphics",
      "Infographic Tools",
      "Chart Tools",
      "Graph Tools",
      "Visualization Tools",
      "Data Visualization",
      "Statistics Graphics",
      "Report Graphics",
      "Document Graphics",
      "Publication Graphics",
      
      // Fashion & Product Design
      "Fashion Design",
      "Product Design",
      "Interior Design",
      "Architecture Design",
      "Landscape Design",
      "Industrial Design",
      "Automotive Design",
      "Furniture Design",
      "Jewelry Design",
      "Textile Design",
      "Pattern Design",
      "Surface Design",
      "Material Design",
      "Color Design",
      "Style Design",
      "Trend Design",
      "Concept Design",
      "Prototype Design",
      "Model Design",
      "3D Design",
      "2D Design",
      "Visual Design",
      "Aesthetic Design",
      "Functional Design",
      "Creative Design",
      "Innovative Design",
      "Modern Design",
      "Contemporary Design",
      "Classic Design",
      "Traditional Design",
      "Minimalist Design",
      "Maximalist Design",
      "Abstract Design",
      "Geometric Design",
      "Organic Design",
      "Natural Design",
      
      // Avatar & Character Design
      "Avatar Generation",
      "Character Design",
      "Character Creation",
      "Avatar Creation",
      "Digital Humans",
      "Virtual Characters",
      "3D Characters",
      "2D Characters",
      "Cartoon Characters",
      "Anime Characters",
      "Realistic Characters",
      "Fantasy Characters",
      "Sci-Fi Characters",
      "Game Characters",
      "Animation Characters",
      "Movie Characters",
      "Story Characters",
      "Book Characters",
      "Comic Characters",
      "Manga Characters",
      "Portrait Generation",
      "Face Generation",
      "Human Generation",
      "People Generation",
      "Person Generation",
      "Individual Generation",
      "Custom Avatars",
      "Personal Avatars",
      "Profile Pictures",
      "Social Media Avatars",
      "Gaming Avatars",
      "Virtual Reality Avatars",
      "Augmented Reality Avatars",
      "Metaverse Avatars",
      
      // Meme & Social Content
      "Meme Generation",
      "Social Content",
      "Viral Content",
      "Entertainment Graphics",
      "Humor Graphics",
      "Comedy Graphics",
      "Fun Graphics",
      "Playful Graphics",
      "Casual Graphics",
      "Lifestyle Graphics",
      "Cultural Graphics",
      "Trend Graphics",
      "Popular Graphics",
      "Contemporary Graphics",
      "Modern Graphics",
      "Digital Graphics",
      "Online Graphics",
      "Internet Graphics",
      "Web Graphics",
      "Mobile Graphics",
      "App Graphics",
      "User Interface Graphics",
      "User Experience Graphics",
      "Interactive Graphics",
      "Dynamic Graphics",
      "Animated Graphics",
      "Motion Graphics",
      "Video Graphics",
      "Multimedia Graphics",
      "Rich Media Graphics",
      
      // Professional & Business Graphics
      "Business Graphics",
      "Corporate Graphics",
      "Professional Graphics",
      "Commercial Graphics",
      "Enterprise Graphics",
      "Office Graphics",
      "Workplace Graphics",
      "Team Graphics",
      "Company Graphics",
      "Organization Graphics",
      "Institution Graphics",
      "Government Graphics",
      "Non-Profit Graphics",
      "Educational Graphics",
      "Academic Graphics",
      "Research Graphics",
      "Scientific Graphics",
      "Technical Graphics",
      "Engineering Graphics",
      "Medical Graphics",
      "Healthcare Graphics",
      "Legal Graphics",
      "Financial Graphics",
      "Banking Graphics",
      "Insurance Graphics",
      "Real Estate Graphics",
      "Construction Graphics",
      "Manufacturing Graphics",
      "Retail Graphics",
      "E-commerce Graphics",
      "Shopping Graphics",
      "Product Graphics",
      "Service Graphics",
      
      // Art & Creative Subcategories
      "Art & Design",
      "Creative AI",
      "Digital Art",
      "Visual Art",
      "Fine Art",
      "Contemporary Art",
      "Modern Art",
      "Abstract Art",
      "Realistic Art",
      "Artistic Creation",
      "Creative Expression",
      "Visual Expression",
      "Artistic Expression",
      "Creative Visualization",
      "Artistic Visualization",
      "Visual Communication",
      "Artistic Communication",
      "Creative Communication",
      "Design Communication",
      "Visual Storytelling",
      "Artistic Storytelling",
      "Creative Storytelling",
      "Design Storytelling",
      "Visual Narrative",
      "Artistic Narrative",
      "Creative Narrative",
      "Design Narrative",
      "Visual Content",
      "Artistic Content",
      "Creative Content",
      "Design Content",
      "Visual Media",
      "Artistic Media",
      "Creative Media",
      "Design Media",
      "Visual Assets",
      "Artistic Assets",
      "Creative Assets",
      "Design Assets"
    ]
  }
];
