
import { MainCategory } from "./types";

export const creativeCategories: MainCategory[] = [
  {
    name: "CREATIVE & ENTERTAINMENT",
    emoji: "🎭",
    description: "Creative tools, entertainment platforms, and artistic AI applications",
    subcategories: [
      // Creative and entertainment categories
      "Creative & Entertainment",
      "Creative & Entertainment (General & Gaming)",
      "Entertainment & Media",
      "Entertainment Tools",
      "Creative Platforms",
      "Creative Services",
      "Creative Suites",
      "Creative Design Tools",
      "Art & Collectibles",
      "Game Design & Development",
      "Entertainment Media Tools",
      "Creative And Entertainment",
      "Communication & Entertainment",
      "Communication And Entertainment",
      "Spirituality & Wellness",
      "Time and History",
      "Time And History",
      "Mysterious And Unusual",
      "Spiritual And Philosophy",
      "Philosophy And Lifestyle",
      "Appraisal And Valuation",
      "Art And Creative",
      "Entertainment And Gaming",
      "Communication And Entertainment",
      "Investigative And Analysis",
      "Creative Writing Tools",
      "Storytelling Tools",
      "Character Creation",
      "Interactive Fiction",
      "Role Playing",
      "Fantasy Tools",
      "Mystical Tools",
      "Fortune Telling",
      "Divination Tools",
      "Spiritual Guidance",
      "Philosophy Tools",
      "Wisdom Tools",
      "Historical Simulation",
      "Time Travel Simulation",
      "Cultural Exploration",
      "Personality Tools",
      "Celebrity Interaction",
      "Entertainment Chat",
      "Fun Tools",
      "Hobby Tools",
      "Lifestyle Tools",
      "Personal Interest"
    ]
  },
  {
    name: "IMAGE & DESIGN AI TOOLS", 
    emoji: "🎨",
    description: "AI-powered image generation, editing, and design tools",
    subcategories: [
      "Image & Design Tools",
      "Image & Design",
      "Image & Design AI Tools",
      "AI Art",
      "Core Image Generators", 
      "Image Editing Tools",
      "Specialized Image Tools",
      "Background & Object Tools",
      "Image Generation Platforms",
      "Design & Graphics Tools",
      "Creative Design",
      "Design Assistant Tools",
      "Graphic Design",
      "Visual Design",
      "Digital Art",
      "Photo Editing",
      "Image Enhancement",
      "Logo Design",
      "Brand Design",
      "Print Design",
      "Web Design Graphics",
      "Social Media Graphics",
      "Marketing Graphics",
      "Illustration Tools",
      "Drawing Tools",
      "Sketch Tools",
      "Coloring Tools",
      "Art Creation",
      "Visual Content"
    ]
  },
  {
    name: "CONTENT CREATION & WRITING",
    emoji: "✍️", 
    description: "AI writing assistants, content generators, and text creation tools",
    subcategories: [
      // CONSOLIDATED: All writing and content categories now under one main category
      "Content Creation & Writing Tools",
      "Writing & Content Creation",
      "Content Creation Tools",
      "Content Creation & Writing Tools", 
      "Writing & Content Enhancement",
      "AI Writing Tools",
      "Writing & Content",
      "Content Creation And Writing Tools",
      "Creative Writing Tools",
      "Grammar And Writing Assistants",
      "Document & Research Tools",
      "Document And Research Tools",
      "Writing Tools",
      "Content Tools",
      "Blog Writing",
      "Article Writing",
      "Script Writing",
      "Book Writing",
      "Story Writing",
      "Poetry Writing",
      "Technical Writing",
      "Academic Writing",
      "Business Writing",
      "Marketing Content",
      "Social Media Content",
      "Email Writing",
      "Copywriting",
      "Content Strategy",
      "Content Planning",
      "Editorial Tools",
      "Publishing Tools",
      "Content Management"
    ]
  }
];
