
import { MainCategory } from "./types";

export const mediaCategories: MainCategory[] = [
  {
    name: "VIDEO & MULTIMEDIA",
    emoji: "🎬",
    description: "AI-powered video creation, editing, and multimedia production tools",
    subcategories: [
      // Core video categories
      "Video Tools",
      "Video Generation Tools", 
      "Video Editing Tools",
      "Advanced Video Tools",
      "Video & Content Tools",
      "Video Editing & Content Tools",
      "Video Marketing Tools",
      "Video Business Tools",
      "Entertainment Media Tools",
      "Video And Content Tools",
      "Video Editing And Content Tools",
      "Video & Content Creation",
      "Video Generation",
      "Video Editing",
      "Video Marketing",
      "Video Business",
      "Multimedia",
      "Multimedia Tools",
      "Content Creation",
      "Entertainment Tools",
      "Creative Tools",
      "Creative Platforms",
      "Creative Services",
      "Creative Suites",
      "Entertainment Media Tools",
      "Creative And Entertainment",
      "Entertainment & Media",
      "Media Tools",
      "Media & Content",
      "Movie Tools",
      "Film Tools",
      "Cinema Tools",
      "Animation Tools",
      // Additional video-related categories that might exist
      "Video Creation",
      "Video Production",
      "Video Synthesis",
      "Video AI",
      "AI Video",
      "Text-to-Video",
      "Image-to-Video",
      "Video Enhancement",
      "Video Processing",
      "Video Automation",
      "Video Content",
      "Video Platforms",
      "Video Generation Platforms",
      "Creative Video Tools",
      "Professional Video Tools",
      "Video Creation Tools",
      "Video Technology",
      "Video Software",
      "Video Applications",
      "Cinematic Tools",
      "Motion Graphics",
      "Visual Effects",
      "Video Effects",
      "Multimedia & Content",
      "Content Creation Tools",
      "Content Creation And Writing Tools",
      "Creative Design Tools",
      "Raw & Uncut Tools"
    ]
  },
  {
    name: "AUDIO & VOICE TOOLS",
    emoji: "🎵",
    description: "AI tools for audio processing, voice synthesis, music generation, and sound editing",
    subcategories: [
      "Audio & Voice Tools",
      "Audio Music Tools",
      "Transcription & Document Tools",
      "Meeting & Transcription Tools",
      "Document And Research Tools",
      "Transcription And Document Tools",
      "Audio Tools",
      "Voice Tools",
      "Music Tools",
      "Audio Generation",
      "Voice Synthesis",
      "Music Generation",
      "Audio Processing",
      "Sound Effects",
      "Audio Enhancement"
    ]
  },
  {
    name: "3D & VISUALIZATION",
    emoji: "🧊",
    description: "AI tools for 3D modeling, visualization, and immersive content creation",
    subcategories: [
      // Core 3D categories
      "3D & Visualization Tools",
      "ThreeD And Visualization Tools",
      "3D Tools",
      "Visualization Tools",
      "3D Modeling",
      "3D Generation",
      "3D Design",
      "Virtual Reality",
      "Augmented Reality",
      "3D Animation",
      
      // Additional 3D-related categories from our tools database
      "AI Art Tools",
      "AI Image Generation", 
      "Image Generation Platforms",
      "Design & Graphics Tools",
      "Creative Design Tools",
      "Image & Design",
      "Image Editing Tools",
      "Specialized Image Tools",
      "Background & Object Tools",
      "Core Image Generators",
      "Design And Graphics Tools",
      "Design Assistant Tools",
      "Creative And Entertainment",
      "Entertainment & Media",
      "Creative Platforms",
      "Creative Services",
      "Creative Suites",
      "Entertainment Media Tools",
      "Multimedia Tools",
      "Visual Effects",
      "Motion Graphics",
      "Rendering Tools",
      "CAD Tools",
      "Architecture Tools",
      "Engineering Tools",
      "Product Design",
      "Industrial Design",
      "Game Design & Development",
      "Game Design And Development",
      
      // Video tools that have 3D capabilities
      "Video Tools",
      "Video Generation Tools",
      "Advanced Video Tools",
      "Video & Content Tools",
      "Video Creation",
      "Video Production",
      "Animation Tools",
      "Cinematic Tools",
      
      // AI generative tools that create 3D content
      "AI Generative Tools",
      "AI Art",
      "Generative Design",
      "Procedural Generation",
      "Text-to-3D",
      "Image-to-3D",
      "AI 3D Generation",
      
      // Technical categories that may contain 3D tools
      "Technical & Utility Tools",
      "Specialized Tools",
      "Professional Tools",
      "Enterprise Tools",
      "Developer Tools",
      "Advanced AI Tools",
      "AI Development Tools",
      "Comprehensive AI Tools",
      
      // Creative categories
      "Art & Creative",
      "Art And Creative",
      "Creative Tools",
      "Artistic Tools",
      "Visual Arts",
      "Digital Art",
      "Concept Art",
      "Character Design",
      "Environment Design",
      "Asset Creation",
      
      // Industry-specific 3D categories
      "Automotive Design",
      "Medical Visualization",
      "Scientific Visualization",
      "Data Visualization",
      "Information Visualization",
      "Interactive Visualization",
      "Real-time Rendering",
      "Ray Tracing",
      "Physics Simulation",
      "Fluid Simulation",
      "Particle Systems",
      "Lighting Simulation",
      "Material Design",
      "Texture Generation",
      "Surface Modeling",
      "Mesh Generation",
      "Point Cloud Processing",
      "Photogrammetry",
      "LiDAR Processing",
      "Volumetric Rendering",
      "Holographic Display",
      "Mixed Reality",
      "Extended Reality",
      "XR Tools",
      "VR Tools",
      "AR Tools",
      "MR Tools",
      "Immersive Experience",
      "Interactive 3D",
      "3D Web",
      "WebGL",
      "Three.js",
      "Unity Tools",
      "Unreal Engine",
      "Blender Tools",
      "Maya Tools",
      "3ds Max",
      "Cinema 4D",
      "Houdini",
      "ZBrush",
      "Substance Tools",
      "Marmoset",
      "KeyShot",
      "V-Ray",
      "Arnold",
      "Octane",
      "Cycles",
      "Mental Ray",
      "RenderMan",
      "Redshift",
      "Corona",
      "FStorm",
      "Clarisse",
      "Katana",
      "Nuke",
      "After Effects 3D",
      "Cinema 4D Lite",
      "Element 3D",
      "Video Copilot",
      "Trapcode",
      "Particular",
      "Form",
      "Mir",
      "Tao",
      "Shine",
      "Lux",
      "Sound Keys",
      "3D Stroke",
      "Plexus",
      "Newton",
      "E3D",
      "Pro Render",
      "Solid Angle",
      "Chaos Group",
      "Pixar",
      "Autodesk",
      "Foundry",
      "SideFX",
      "Maxon",
      "Adobe 3D",
      "Nvidia Omniverse",
      "Epic Games",
      "Unity Technologies",
      "Sketchfab",
      "TurboSquid",
      "CGTrader",
      "Artstation",
      "Polycount",
      "ZBrushCentral",
      "BlenderArtists",
      "CGSociety",
      "3DTotal",
      "3DArtist",
      "CGChannel",
      "3DWorld",
      "Computer Arts",
      "Digital Arts",
      "Creative Bloq",
      "Behance 3D",
      "Dribbble 3D",
      "Pinterest 3D",
      "Instagram 3D",
      "YouTube 3D",
      "Vimeo 3D",
      "Facebook 3D",
      "Twitter 3D",
      "LinkedIn 3D",
      "Reddit 3D",
      "Discord 3D",
      "Slack 3D",
      "Telegram 3D",
      "WhatsApp 3D",
      "WeChat 3D",
      "TikTok 3D",
      "Snapchat 3D",
      "Twitch 3D",
      "Steam 3D",
      "Epic Store 3D",
      "GOG 3D",
      "Itch.io 3D",
      "Game Jolt 3D",
      "Newgrounds 3D",
      "DeviantArt 3D",
      "Flickr 3D",
      "500px 3D",
      "SmugMug 3D",
      "Google Photos 3D",
      "iCloud Photos 3D",
      "OneDrive 3D",
      "Dropbox 3D",
      "Google Drive 3D",
      "Box 3D",
      "WeTransfer 3D",
      "Send Anywhere 3D",
      "Mega 3D",
      "MediaFire 3D"
    ]
  }
];
