
import { MainCategory } from "./types";

export const mediaCategories: MainCategory[] = [
  {
    name: "VIDEO & MULTIMEDIA",
    emoji: "🎬",
    description: "AI-powered video creation, editing, and multimedia production tools",
    subcategories: [
      // Core video categories
      "Video Tools",
      "Video Generation Tools", 
      "Video Editing Tools",
      "Advanced Video Tools",
      "Video & Content Tools",
      "Video Editing & Content Tools",
      "Video Marketing Tools",
      "Video Business Tools",
      "Entertainment Media Tools",
      "Video And Content Tools",
      "Video Editing And Content Tools",
      "Video & Content Creation",
      "Video Generation",
      "Video Editing",
      "Video Marketing",
      "Video Business",
      "Multimedia",
      "Multimedia Tools",
      "Content Creation",
      "Entertainment Tools",
      "Creative Tools",
      "Creative Platforms",
      "Creative Services",
      "Creative Suites",
      "Entertainment Media Tools",
      "Creative And Entertainment",
      "Entertainment & Media",
      "Media Tools",
      "Media & Content",
      "Movie Tools",
      "Film Tools",
      "Cinema Tools",
      "Animation Tools",
      
      // Video Generation & AI Video
      "Video Creation",
      "Video Production",
      "Video Synthesis",
      "Video AI",
      "AI Video",
      "Text-to-Video",
      "Image-to-Video",
      "Video Enhancement",
      "Video Processing",
      "Video Automation",
      "Video Content",
      "Video Platforms",
      "Video Generation Platforms",
      "Creative Video Tools",
      "Professional Video Tools",
      "Video Creation Tools",
      "Video Technology",
      "Video Software",
      "Video Applications",
      "Cinematic Tools",
      "Motion Graphics",
      "Visual Effects",
      "Video Effects",
      "Multimedia & Content",
      "Content Creation Tools",
      "Content Creation And Writing Tools",
      "Creative Design Tools",
      "Raw & Uncut Tools",
      
      // Video & Animation Tools
      "Video & Animation Tools",
      "Animation",
      "3D Animation",
      "2D Animation",
      "Character Animation",
      "Motion Animation",
      "Animated Content",
      "Animation Creation",
      "Animation Studio",
      "Animation Platform",
      "Animation Software",
      "Interactive Animation",
      "Real-time Animation",
      "Video Animation",
      "Animated Video",
      "Animated Stories",
      "Animated Presentations",
      "Animated Marketing",
      "Animated Education",
      "Animated Entertainment",
      
      // Avatar & Character Video
      "Avatar Creation",
      "Digital Avatars",
      "Virtual Avatars",
      "AI Avatars",
      "Interactive Avatars",
      "Avatar Video",
      "Avatar Generation",
      "Avatar Technology",
      "Avatar Platforms",
      "Avatar Services",
      "Character Video",
      "Digital Characters",
      "Virtual Characters",
      "AI Characters",
      "Interactive Characters",
      "Character Creation",
      "Character Animation",
      "Character Synthesis",
      
      // Video Editing & Post-Production
      "Video Editor",
      "Video Editing Software",
      "Video Editing Platform",
      "Video Post-Production",
      "Video Enhancement Tools",
      "Video Optimization",
      "Video Quality Enhancement",
      "Video Restoration",
      "Video Correction",
      "Video Filters",
      "Video Transitions",
      "Video Templates",
      "Video Assets",
      "Video Resources",
      "Video Libraries",
      "Video Stock",
      "Video Footage",
      "Video Clips",
      "Video Segments",
      "Video Sequences",
      
      // Multimedia Production
      "Multimedia Production",
      "Multimedia Creation",
      "Multimedia Editing",
      "Multimedia Platform",
      "Multimedia Studio",
      "Multimedia Suite",
      "Multimedia Technology",
      "Rich Media",
      "Interactive Media",
      "Digital Media",
      "Media Production",
      "Media Creation",
      "Media Editing",
      "Media Management",
      "Media Processing",
      "Media Enhancement",
      "Media Optimization",
      "Media Distribution",
      "Media Publishing",
      "Media Sharing",
      
      // Creative & Design Tools (Video-focused)
      "Creative & Design Tools",
      "Creative & Media",
      "Creative & Entertainment",
      "Creative Video",
      "Creative Content",
      "Creative Production",
      "Creative Studio",
      "Creative Platform",
      "Creative Suite",
      "Creative Services",
      "Creative Solutions",
      "Creative Technology",
      "Creative Software",
      "Creative Applications",
      "Creative Workflows",
      "Creative Automation",
      "Creative AI",
      "Creative Generation",
      "Creative Enhancement",
      
      // Video Marketing & Business
      "Video Marketing",
      "Marketing Video",
      "Business Video",
      "Corporate Video",
      "Commercial Video",
      "Promotional Video",
      "Advertisement Video",
      "Social Media Video",
      "Video Campaigns",
      "Video Branding",
      "Video Communication",
      "Video Presentations",
      "Video Training",
      "Video Education",
      "Video Learning",
      "Video Courses",
      "Video Tutorials",
      "Video Demonstrations",
      "Video Explanations",
      "Video Documentation",
      
      // Specialized Video Tools
      "Music Video",
      "Music Video Creation",
      "Music Video Production",
      "Music Video Editing",
      "Movie Making",
      "Film Making",
      "Filmmaking",
      "Cinema Production",
      "Short Films",
      "Video Podcasts",
      "Podcast Video",
      "Live Streaming",
      "Stream Production",
      "Broadcasting",
      "Video Broadcasting",
      "Video Streaming",
      "Real-time Video",
      "Interactive Video",
      "Immersive Video",
      "360 Video",
      "VR Video",
      "AR Video",
      "Mixed Reality Video",
      
      // Video AI Technologies
      "Generative Video",
      "AI Video Generation",
      "Machine Learning Video",
      "Deep Learning Video",
      "Neural Video",
      "Computer Vision Video",
      "Video Recognition",
      "Video Analysis",
      "Video Intelligence",
      "Video Automation",
      "Automated Video",
      "Smart Video",
      "Intelligent Video",
      "Adaptive Video",
      "Personalized Video",
      "Custom Video",
      "Tailored Video",
      "Dynamic Video",
      "Responsive Video",
      "Interactive Video Content",
      
      // Performance & Stage Tools
      "Performing Arts",
      "Stage Production",
      "Theater Production",
      "Performance Tools",
      "Stage Management",
      "Production Management",
      "Event Production",
      "Live Performance",
      "Stage Technology",
      "Performance Technology",
      "Entertainment Production",
      "Show Production",
      "Concert Production",
      "Festival Production",
      "Performance Arts",
      "Creative Performance",
      "Digital Performance",
      "Virtual Performance",
      "Hybrid Performance",
      "Interactive Performance",
      
      // Video Collaboration & Workflow
      "Video Collaboration",
      "Collaborative Video",
      "Team Video",
      "Video Workflow",
      "Video Pipeline",
      "Video Project Management",
      "Video Asset Management",
      "Video Version Control",
      "Video Review",
      "Video Approval",
      "Video Feedback",
      "Video Comments",
      "Video Annotation",
      "Video Markup",
      "Video Revision",
      "Video Iteration",
      "Video Development",
      "Video Prototyping",
      "Video Testing",
      "Video Quality Assurance",
      
      // Video Format & Technical
      "Video Formats",
      "Video Encoding",
      "Video Decoding",
      "Video Compression",
      "Video Conversion",
      "Video Transcoding",
      "Video Streaming",
      "Video Delivery",
      "Video CDN",
      "Video Infrastructure",
      "Video Hosting",
      "Video Storage",
      "Video Backup",
      "Video Archive",
      "Video Library Management",
      "Video Catalog",
      "Video Search",
      "Video Discovery",
      "Video Recommendation",
      "Video Analytics",
      
      // E-commerce & Marketing Video Tools
      "E-commerce Video",
      "Product Video",
      "Demo Video",
      "Tutorial Video",
      "How-to Video",
      "Explainer Video",
      "Training Video",
      "Onboarding Video",
      "Sales Video",
      "Marketing Automation Video",
      "Personalized Marketing Video",
      "Video Email Marketing",
      "Video Social Media",
      "Video Advertising",
      "Video Campaigns",
      "Video ROI",
      "Video Metrics",
      "Video Performance",
      "Video Optimization",
      "Video Testing"
    ]
  },
  {
    name: "AUDIO & VOICE TOOLS",
    emoji: "🎵",
    description: "AI tools for audio processing, voice synthesis, music generation, and sound editing",
    subcategories: [
      "Audio & Voice Tools",
      "Audio Music Tools",
      "Transcription & Document Tools",
      "Meeting & Transcription Tools",
      "Document And Research Tools",
      "Transcription And Document Tools",
      "Audio Tools",
      "Voice Tools",
      "Music Tools",
      "Audio Generation",
      "Voice Synthesis",
      "Music Generation",
      "Audio Processing",
      "Sound Effects",
      "Audio Enhancement"
    ]
  },
  {
    name: "3D & VISUALIZATION",
    emoji: "🧊",
    description: "AI tools for 3D modeling, visualization, and immersive content creation",
    subcategories: [
      // Core 3D categories
      "3D & Visualization Tools",
      "ThreeD And Visualization Tools",
      "3D Tools",
      "Visualization Tools",
      "3D Modeling",
      "3D Generation",
      "3D Design",
      "Virtual Reality",
      "Augmented Reality",
      "3D Animation",
      "3D Rendering",
      "3D Visualization",
      "Mixed Reality",
      "Extended Reality",
      "XR Tools",
      "VR Tools",
      "AR Tools",
      "MR Tools",
      "Immersive Experience",
      "Interactive 3D",
      "3D Web",
      "Text-to-3D",
      "Image-to-3D",
      "AI 3D Generation",
      "3D Art",
      "3D Graphics",
      "3D Models",
      "3D Assets",
      "3D Content",
      "3D Creation",
      "3D Development",
      "3D Technology",
      "3D Software",
      "3D Applications",
      "3D Platforms",
      "Volumetric Rendering",
      "Ray Tracing",
      "Real-time Rendering",
      "Physics Simulation",
      "Fluid Simulation",
      "Particle Systems",
      "Lighting Simulation",
      "Material Design",
      "Texture Generation",
      "Surface Modeling",
      "Mesh Generation",
      "Point Cloud Processing",
      "Photogrammetry",
      "LiDAR Processing",
      "Holographic Display",
      "CAD Tools",
      "Architecture Tools",
      "Engineering Tools",
      "Product Design",
      "Industrial Design",
      "Automotive Design",
      "Medical Visualization",
      "Scientific Visualization",
      "Data Visualization",
      "Information Visualization",
      "Interactive Visualization"
    ]
  }
];
