
import { MainCategory } from "./types";

export const mediaCategories: MainCategory[] = [
  {
    name: "VIDEO & MULTIMEDIA",
    emoji: "🎬",
    description: "AI-powered video creation, editing, and multimedia production tools",
    subcategories: [
      // Core video categories
      "Video Tools",
      "Video Generation Tools", 
      "Video Editing Tools",
      "Advanced Video Tools",
      "Video & Content Tools",
      "Video Editing & Content Tools",
      "Video Marketing Tools",
      "Video Business Tools",
      "Entertainment Media Tools",
      "Video And Content Tools",
      "Video Editing And Content Tools",
      "Video & Content Creation",
      "Video Generation",
      "Video Editing",
      "Video Marketing",
      "Video Business",
      "Multimedia",
      "Multimedia Tools",
      "Content Creation",
      "Entertainment Tools",
      "Creative Tools",
      "Creative Platforms",
      "Creative Services",
      "Creative Suites",
      "Entertainment Media Tools",
      "Creative And Entertainment",
      "Entertainment & Media",
      "Media Tools",
      "Media & Content",
      "Movie Tools",
      "Film Tools",
      "Cinema Tools",
      "Animation Tools",
      "Video Creation",
      "Video Production",
      "Video Synthesis",
      "Video AI",
      "AI Video",
      "Text-to-Video",
      "Image-to-Video",
      "Video Enhancement",
      "Video Processing",
      "Video Automation",
      "Video Content",
      "Video Platforms",
      "Video Generation Platforms",
      "Creative Video Tools",
      "Professional Video Tools",
      "Video Creation Tools",
      "Video Technology",
      "Video Software",
      "Video Applications",
      "Cinematic Tools",
      "Motion Graphics",
      "Visual Effects",
      "Video Effects",
      "Multimedia & Content",
      "Content Creation Tools",
      "Content Creation And Writing Tools",
      "Creative Design Tools",
      "Raw & Uncut Tools",
      "Video & Animation Tools",
      "Animation",
      "3D Animation",
      "2D Animation",
      "Character Animation",
      "Motion Animation",
      "Animated Content",
      "Animation Creation",
      "Animation Studio",
      "Animation Platform",
      "Animation Software",
      "Interactive Animation",
      "Real-time Animation",
      "Video Animation",
      "Animated Video",
      "Animated Stories",
      "Animated Presentations",
      "Animated Marketing",
      "Animated Education",
      "Animated Entertainment",
      "Avatar Creation",
      "Digital Avatars",
      "Virtual Avatars",
      "AI Avatars",
      "Interactive Avatars",
      "Avatar Video",
      "Avatar Generation",
      "Avatar Technology",
      "Avatar Platforms",
      "Avatar Services",
      "Character Video",
      "Digital Characters",
      "Virtual Characters",
      "AI Characters",
      "Interactive Characters",
      "Character Creation",
      "Character Animation",
      "Character Synthesis",
      "Video Editor",
      "Video Editing Software",
      "Video Editing Platform",
      "Video Post-Production",
      "Video Enhancement Tools",
      "Video Optimization",
      "Video Quality Enhancement",
      "Video Restoration",
      "Video Correction",
      "Video Filters",
      "Video Transitions",
      "Video Templates",
      "Video Assets",
      "Video Resources",
      "Video Libraries",
      "Video Stock",
      "Video Footage",
      "Video Clips",
      "Video Segments",
      "Video Sequences",
      "Multimedia Production",
      "Multimedia Creation",
      "Multimedia Editing",
      "Multimedia Platform",
      "Multimedia Studio",
      "Multimedia Suite",
      "Multimedia Technology",
      "Rich Media",
      "Interactive Media",
      "Digital Media",
      "Media Production",
      "Media Creation",
      "Media Editing",
      "Media Management",
      "Media Processing",
      "Media Enhancement",
      "Media Optimization",
      "Media Distribution",
      "Media Publishing",
      "Media Sharing",
      "Creative & Design Tools",
      "Creative & Media",
      "Creative & Entertainment",
      "Creative Video",
      "Creative Content",
      "Creative Production",
      "Creative Studio",
      "Creative Platform",
      "Creative Suite",
      "Creative Services",
      "Creative Solutions",
      "Creative Technology",
      "Creative Software",
      "Creative Applications",
      "Creative Workflows",
      "Creative Automation",
      "Creative AI",
      "Creative Generation",
      "Creative Enhancement",
      "Video Marketing",
      "Marketing Video",
      "Business Video",
      "Corporate Video",
      "Commercial Video",
      "Promotional Video",
      "Advertisement Video",
      "Social Media Video",
      "Video Campaigns",
      "Video Branding",
      "Video Communication",
      "Video Presentations",
      "Video Training",
      "Video Education",
      "Video Learning",
      "Video Courses",
      "Video Tutorials",
      "Video Demonstrations",
      "Video Explanations",
      "Video Documentation",
      "Music Video",
      "Music Video Creation",
      "Music Video Production",
      "Music Video Editing",
      "Movie Making",
      "Film Making",
      "Filmmaking",
      "Cinema Production",
      "Short Films",
      "Video Podcasts",
      "Podcast Video",
      "Live Streaming",
      "Stream Production",
      "Broadcasting",
      "Video Broadcasting",
      "Video Streaming",
      "Real-time Video",
      "Interactive Video",
      "Immersive Video",
      "360 Video",
      "VR Video",
      "AR Video",
      "Mixed Reality Video",
      "Generative Video",
      "AI Video Generation",
      "Machine Learning Video",
      "Deep Learning Video",
      "Neural Video",
      "Computer Vision Video",
      "Video Recognition",
      "Video Analysis",
      "Video Intelligence",
      "Video Automation",
      "Automated Video",
      "Smart Video",
      "Intelligent Video",
      "Adaptive Video",
      "Personalized Video",
      "Custom Video",
      "Tailored Video",
      "Dynamic Video",
      "Responsive Video",
      "Interactive Video Content",
      "Performing Arts",
      "Stage Production",
      "Theater Production",
      "Performance Tools",
      "Stage Management",
      "Production Management",
      "Event Production",
      "Live Performance",
      "Stage Technology",
      "Performance Technology",
      "Entertainment Production",
      "Show Production",
      "Concert Production",
      "Festival Production",
      "Performance Arts",
      "Creative Performance",
      "Digital Performance",
      "Virtual Performance",
      "Hybrid Performance",
      "Interactive Performance",
      "Video Collaboration",
      "Collaborative Video",
      "Team Video",
      "Video Workflow",
      "Video Pipeline",
      "Video Project Management",
      "Video Asset Management",
      "Video Version Control",
      "Video Review",
      "Video Approval",
      "Video Feedback",
      "Video Comments",
      "Video Annotation",
      "Video Markup",
      "Video Revision",
      "Video Iteration",
      "Video Development",
      "Video Prototyping",
      "Video Testing",
      "Video Quality Assurance",
      "Video Formats",
      "Video Encoding",
      "Video Decoding",
      "Video Compression",
      "Video Conversion",
      "Video Transcoding",
      "Video Streaming",
      "Video Delivery",
      "Video CDN",
      "Video Infrastructure",
      "Video Hosting",
      "Video Storage",
      "Video Backup",
      "Video Archive",
      "Video Library Management",
      "Video Catalog",
      "Video Search",
      "Video Discovery",
      "Video Recommendation",
      "Video Analytics",
      "E-commerce Video",
      "Product Video",
      "Demo Video",
      "Tutorial Video",
      "How-to Video",
      "Explainer Video",
      "Training Video",
      "Onboarding Video",
      "Sales Video",
      "Marketing Automation Video",
      "Personalized Marketing Video",
      "Video Email Marketing",
      "Video Social Media",
      "Video Advertising",
      "Video Campaigns",
      "Video ROI",
      "Video Metrics",
      "Video Performance",
      "Video Optimization",
      "Video Testing"
    ]
  },
  {
    name: "AUDIO & VOICE TOOLS",
    emoji: "🎵",
    description: "AI tools for audio processing, voice synthesis, music generation, and sound editing",
    subcategories: [
      // Core audio categories
      "Audio & Voice Tools",
      "Audio Music Tools",
      "Audio Tools",
      "Voice Tools",
      "Music Tools",
      "Audio Generation",
      "Voice Synthesis",
      "Music Generation",
      "Audio Processing",
      "Sound Effects",
      "Audio Enhancement",
      "Audio & Music Tools",
      "Audio AI",
      "Voice AI",
      "Speech AI",
      "Audio Production",
      "Voice Generation",
      "Speech Generation",
      "Music Creation",
      "Audio Creation",
      "Sound Generation",
      "Voice Cloning",
      "Speech Synthesis",
      "Text-to-Speech",
      "TTS",
      "Voice Over",
      "Narration",
      "Audio Editing",
      "Sound Editing",
      "Music Editing",
      "Voice Editing",
      "Audio Engineering",
      "Sound Engineering",
      "Music Engineering",
      "Voice Engineering",
      "Transcription & Document Tools",
      "Meeting & Transcription Tools",
      "Document And Research Tools",
      "Transcription And Document Tools",
      "Speech-to-Text",
      "STT",
      "Audio Transcription",
      "Voice Transcription",
      "Meeting Transcription",
      "Podcast Transcription",
      "Interview Transcription",
      "Dictation",
      "Voice Notes",
      "Audio Notes",
      "AI Music Generation",
      "Music Composition",
      "AI Composition",
      "Algorithmic Composition",
      "Generative Music",
      "AI Music",
      "Machine Learning Music",
      "Neural Music",
      "Music AI",
      "Automated Music",
      "Smart Music",
      "Intelligent Music",
      "Adaptive Music",
      "Interactive Music",
      "Procedural Music",
      "Dynamic Music",
      "Personalized Music",
      "Custom Music",
      "Royalty-free Music",
      "Background Music",
      "Ambient Music",
      "Instrumental Music",
      "Soundtrack Music",
      "Commercial Music",
      "Mood Music",
      "Genre Music",
      "Style Music",
      "Voice Transformation",
      "Voice Modulation",
      "Voice Effects",
      "Voice Filters",
      "Real-time Voice",
      "Live Voice",
      "Voice Chat",
      "Voice Communication",
      "Voice Calling",
      "Voice Conferencing",
      "Voice Streaming",
      "Voice Broadcasting",
      "Voice Recording",
      "Voice Capture",
      "Voice Recognition",
      "Voice Analysis",
      "Voice Intelligence",
      "Voice Automation",
      "Voice Assistants",
      "Conversational AI",
      "Voice Bots",
      "Speech Bots",
      "Voice Agents",
      "Speech Agents",
      "Audio Cleanup",
      "Audio Restoration",
      "Audio Mastering",
      "Audio Mixing",
      "Audio Compression",
      "Audio Normalization",
      "Audio Optimization",
      "Audio Quality",
      "Audio Improvement",
      "Audio Upscaling",
      "Audio Upsampling",
      "Audio Denoising",
      "Noise Removal",
      "Noise Reduction",
      "Noise Cancellation",
      "Echo Removal",
      "Reverb Removal",
      "Audio Clarity",
      "Voice Clarity",
      "Speech Clarity",
      "Audio Filtering",
      "Audio EQ",
      "Audio Equalization",
      "Audio Balance",
      "Audio Stereo",
      "Audio Mono",
      "Audio Channels",
      "Music Production",
      "Music Studio",
      "Digital Audio Workstation",
      "DAW",
      "Music Software",
      "Music Platform",
      "Music Suite",
      "Music Toolkit",
      "Beat Making",
      "Beat Production",
      "Drum Machine",
      "Drum Sequencer",
      "Music Sequencer",
      "MIDI",
      "Audio Samples",
      "Music Samples",
      "Sound Samples",
      "Audio Loops",
      "Music Loops",
      "Sound Loops",
      "Audio Assets",
      "Music Assets",
      "Sound Assets",
      "Audio Library",
      "Music Library",
      "Sound Library",
      "Sample Library",
      "Preset Library",
      "Podcast Tools",
      "Podcast Production",
      "Podcast Editing",
      "Podcast Creation",
      "Podcast Publishing",
      "Podcast Enhancement",
      "Podcast Automation",
      "Broadcasting Tools",
      "Radio Tools",
      "Streaming Tools",
      "Live Audio",
      "Audio Streaming",
      "Audio Broadcasting",
      "Audio Publishing",
      "Audio Distribution",
      "Audio Hosting",
      "Audio CDN",
      "Audio Platform",
      "Spatial Audio",
      "3D Audio",
      "Surround Sound",
      "Binaural Audio",
      "Immersive Audio",
      "VR Audio",
      "AR Audio",
      "Interactive Audio",
      "Game Audio",
      "Video Game Audio",
      "Film Audio",
      "Movie Audio",
      "TV Audio",
      "Commercial Audio",
      "Advertisement Audio",
      "Marketing Audio",
      "Educational Audio",
      "Training Audio",
      "Corporate Audio",
      "Business Audio",
      "Professional Audio",
      "Studio Audio",
      "Live Audio",
      "Concert Audio",
      "Performance Audio",
      "Event Audio",
      "Audio Formats",
      "Audio Conversion",
      "Audio Encoding",
      "Audio Decoding",
      "Audio Compression",
      "Audio Codecs",
      "Audio Quality",
      "Audio Bitrate",
      "Audio Sample Rate",
      "Audio Resolution",
      "High-Quality Audio",
      "Lossless Audio",
      "Lossy Audio",
      "Audio Standards",
      "Audio Protocols",
      "Audio APIs",
      "Audio SDKs",
      "Audio Frameworks",
      "Audio Libraries",
      "Audio Tools",
      "Audio Utilities",
      "Audio Software",
      "Audio Applications",
      "Audio Programs",
      "Audio Systems",
      "Audio Infrastructure",
      "Audio Technology",
      "Celebrity Voices",
      "Character Voices",
      "Custom Voices",
      "Professional Voices",
      "Natural Voices",
      "Human Voices",
      "Realistic Voices",
      "Lifelike Voices",
      "Multilingual Voices",
      "Language Voices",
      "Accent Voices",
      "Regional Voices",
      "Gender Voices",
      "Age Voices",
      "Emotion Voices",
      "Expressive Voices",
      "Conversational Voices",
      "Narrative Voices",
      "Storytelling Voices",
      "Educational Voices",
      "Commercial Voices",
      "Advertisement Voices",
      "Marketing Voices",
      "Corporate Voices",
      "Business Voices",
      "Neural Audio",
      "Deep Learning Audio",
      "Machine Learning Audio",
      "AI Audio Processing",
      "Audio Intelligence",
      "Smart Audio",
      "Intelligent Audio",
      "Adaptive Audio",
      "Responsive Audio",
      "Context-Aware Audio",
      "Personalized Audio",
      "Custom Audio",
      "Tailored Audio",
      "Dynamic Audio",
      "Interactive Audio",
      "Immersive Audio Experience",
      "Audio Innovation",
      "Audio Research",
      "Audio Development",
      "Audio Experimentation",
      "Audio Prototyping",
      "Audio Testing",
      "Audio Validation",
      "Audio Optimization",
      "Audio Performance"
    ]
  },
  {
    name: "3D & VISUALIZATION",
    emoji: "🧊",
    description: "AI tools for 3D modeling, visualization, and immersive content creation",
    subcategories: [
      // Core 3D categories
      "3D & Visualization Tools",
      "ThreeD And Visualization Tools",
      "3D Tools",
      "Visualization Tools",
      "3D Modeling",
      "3D Generation",
      "3D Design",
      "Virtual Reality",
      "Augmented Reality",
      "3D Animation",
      "3D Rendering",
      "3D Visualization",
      "Mixed Reality",
      "Extended Reality",
      "XR Tools",
      "VR Tools",
      "AR Tools",
      "MR Tools",
      "Immersive Experience",
      "Interactive 3D",
      "3D Web",
      "Text-to-3D",
      "Image-to-3D",
      "AI 3D Generation",
      "3D Art",
      "3D Graphics",
      "3D Models",
      "3D Assets",
      "3D Content",
      "3D Creation",
      "3D Development",
      "3D Technology",
      "3D Software",
      "3D Applications",
      "3D Platforms",
      "Volumetric Rendering",
      "Ray Tracing",
      "Real-time Rendering",
      "Physics Simulation",
      "Fluid Simulation",
      "Particle Systems",
      "Lighting Simulation",
      "Material Design",
      "Texture Generation",
      "Surface Modeling",
      "Mesh Generation",
      "Point Cloud Processing",
      "Photogrammetry",
      "LiDAR Processing",
      "Holographic Display",
      "CAD Tools",
      "Architecture Tools",
      "Engineering Tools",
      "Product Design",
      "Industrial Design",
      "Automotive Design",
      "Medical Visualization",
      "Scientific Visualization",
      "Data Visualization",
      "Information Visualization",
      "Interactive Visualization",
      
      // Enhanced 3D categories for the specific tools mentioned
      "3D Printing",
      "3D Print Tools",
      "3D Print GPT",
      "Text to 3D Generation",
      "Meshy AI",
      "Meshy",
      "Spline",
      "Spline 3D",
      "Luma AI",
      "Luma 3D",
      "3D Capture",
      "3D Scanning",
      "Polycam",
      "Blender",
      "Blender 3D",
      "Open Source 3D",
      "3D Modeling Software",
      "Professional 3D Tools",
      "3D Creation Platforms",
      "AI 3D Tools",
      "Machine Learning 3D",
      "Neural 3D Generation",
      "Procedural 3D",
      "Generative 3D",
      "3D Prototyping",
      "3D Production",
      "3D Workflow",
      "3D Pipeline",
      "3D Asset Creation",
      "3D Content Creation",
      "3D Digital Assets",
      "3D Scene Creation",
      "3D Environment Design",
      "3D Character Modeling",
      "3D Object Modeling",
      "3D Reconstruction",
      "3D Digitization",
      "3D Documentation",
      "3D Archiving",
      "3D Preservation",
      "3D Analysis",
      "3D Measurement",
      "3D Inspection",
      "3D Quality Control",
      "3D Manufacturing",
      "3D Production Tools",
      "3D Design Software",
      "3D Creative Tools",
      "3D Artist Tools",
      "3D Designer Tools",
      "3D Developer Tools",
      "3D Engineer Tools",
      "3D Architect Tools",
      "Business Operations",
      "Productivity"
    ]
  }
];
