import { MainCategory } from "./types";

export const serviceCategories: MainCategory[] = [
  {
    name: "EDUCATION & LEARNING",
    emoji: "🎓",
    description: "AI-powered educational tools, learning platforms, and knowledge management systems",
    subcategories: [
      // Core education categories
      "Education & Learning",
      "Learning & Education",
      "Learning Platforms",
      "Research & Learning",
      "Education And Learning",
      "Learning And Education", 
      "Research And Learning",
      "AI Education Tools",
      "AI Research Tools",
      "Educational Tools",
      "Learning Tools",
      "Study Tools",
      "Academic Tools",
      "Course Creation",
      "Course Development",
      "Learning Management",
      "Educational Technology",
      "E-Learning",
      "Online Learning",
      "Distance Learning",
      "Educational Content",
      "Learning Content",
      "Educational Resources",
      "Learning Resources",
      "Study Resources",
      "Academic Resources",
      "Educational Platforms",
      "Learning Platforms",
      "Study Platforms",
      "Academic Platforms",
      "Educational Software",
      "Learning Software",
      "Study Software",
      "Academic Software",
      "Educational Systems",
      "Learning Systems",
      "Study Systems",
      "Academic Systems",
      "Educational Support",
      "Learning Support",
      "Study Support",
      "Academic Support",
      "Educational Assistance",
      "Learning Assistance",
      "Study Assistance",
      "Academic Assistance",
      "Educational Guidance",
      "Learning Guidance",
      "Study Guidance",
      "Academic Guidance",
      "Educational Coaching",
      "Learning Coaching",
      "Study Coaching",
      "Academic Coaching",
      "Educational Tutoring",
      "Learning Tutoring",
      "Study Tutoring",
      "Academic Tutoring",
      "Skill Development",
      "Skill Building",
      "Skill Enhancement",
      "Skill Training",
      "Professional Development",
      "Personal Development",
      "Career Development",
      "Knowledge Management",
      "Knowledge Sharing",
      "Knowledge Transfer",
      "Information Learning",
      "Data Learning",
      "Research Tools",
      "Study Planning",
      "Learning Planning",
      "Educational Planning",
      "Academic Planning",
      "Curriculum Planning",
      "Course Planning",
      "Lesson Planning",
      "Study Scheduling",
      "Learning Scheduling",
      "Educational Scheduling",
      "Academic Scheduling",
      "Progress Tracking",
      "Learning Progress",
      "Educational Progress",
      "Academic Progress",
      "Performance Tracking",
      "Learning Performance",
      "Educational Performance",
      "Academic Performance",
      "Assessment Tools",
      "Testing Tools",
      "Quiz Tools",
      "Evaluation Tools",
      "Grading Tools",
      "Feedback Tools",
      "Review Tools",
      "Analysis Tools",
      "Learning Analytics",
      "Educational Analytics",
      "Academic Analytics",
      "Student Analytics",
      "Learning Insights",
      "Educational Insights",
      "Academic Insights",
      "Student Insights",
      "Personalized Learning",
      "Adaptive Learning",
      "Customized Learning",
      "Individualized Learning",
      "Self-Paced Learning",
      "Interactive Learning",
      "Engaging Learning",
      "Immersive Learning",
      "Gamified Learning",
      "Social Learning",
      "Collaborative Learning",
      "Group Learning",
      "Team Learning",
      "Peer Learning",
      "Community Learning",
      "Mobile Learning",
      "Microlearning",
      "Bite-sized Learning",
      "Just-in-time Learning",
      "Continuous Learning",
      "Lifelong Learning",
      "Professional Learning",
      "Corporate Learning",
      "Enterprise Learning",
      "Business Learning",
      "Workplace Learning",
      "Training Tools",
      "Training Platforms",
      "Training Systems",
      "Training Software",
      "Training Programs",
      "Training Materials",
      "Training Resources",
      "Training Content",
      "Certification Tools",
      "Accreditation Tools",
      "Credentialing Tools",
      "Badge Systems",
      "Achievement Systems",
      "Reward Systems",
      "Recognition Systems",
      "Motivation Tools",
      "Engagement Tools",
      "Retention Tools",
      "Completion Tools",
      // Specific tool categories for education
      "College Education",
      "University Education",
      "Higher Education",
      "Degree Programs",
      "Course Learning",
      "Skill Learning",
      "Language Learning",
      "Coding Education",
      "Programming Education",
      "Math Education",
      "Science Education",
      "History Education",
      "Literature Education",
      "Arts Education",
      "Music Education",
      "Physical Education",
      "Health Education",
      "Safety Education",
      "Homeschooling",
      "Home Education",
      "Private Education",
      "Public Education",
      "Alternative Education",
      "Special Education",
      "Gifted Education",
      "Adult Education",
      "Continuing Education",
      "Vocational Education",
      "Technical Education",
      "Trade Education",
      "Professional Education",
      "Executive Education",
      "Leadership Education",
      "Management Education",
      "Entrepreneurship Education",
      "Financial Education",
      "Computer Science Education",
      "Engineering Education",
      "Medical Education",
      "Legal Education",
      "Business Education",
      "Marketing Education",
      "Sales Education",
      "Customer Service Education",
      "Communication Education",
      "Presentation Education",
      "Writing Education",
      "Reading Education",
      "Grammar Education",
      "Vocabulary Education",
      "Spelling Education",
      "Pronunciation Education",
      "Listening Education",
      "Speaking Education",
      "Conversation Education",
      "Cultural Education",
      "Environmental Education",
      "Sustainability Education",
      "Ethics Education",
      "Philosophy Education",
      "Psychology Education",
      "Sociology Education",
      "Anthropology Education",
      "Geography Education",
      "Economics Education",
      "Political Science Education",
      "International Relations Education",
      "Criminal Justice Education",
      "Social Work Education",
      "Counseling Education",
      "Therapy Education",
      "Rehabilitation Education",
      "Occupational Therapy Education",
      "Physical Therapy Education",
      "Speech Therapy Education",
      "Mental Health Education",
      "Wellness Education",
      "Nutrition Education",
      "Fitness Education",
      "Sports Education",
      "Recreation Education",
      "Leisure Education",
      "Hobby Education",
      "Crafts Education",
      "DIY Education",
      "Maker Education",
      "STEM Education",
      "STEAM Education",
      "Research Education",
      "Scientific Method Education",
      "Critical Thinking Education",
      "Problem Solving Education",
      "Decision Making Education",
      "Creativity Education",
      "Innovation Education",
      "Design Thinking Education",
      "Project Management Education",
      "Time Management Education",
      "Organization Education",
      "Study Skills Education",
      "Test Taking Education",
      "Memory Improvement Education",
      "Speed Reading Education",
      "Note Taking Education",
      "Research Skills Education",
      "Information Literacy Education",
      "Digital Literacy Education",
      "Media Literacy Education",
      "Technology Education",
      "Computer Literacy Education",
      "Internet Safety Education",
      "Cybersecurity Education",
      "Data Privacy Education",
      "Ethics in Technology Education"
    ]
  },
  {
    name: "HEALTH & WELLNESS",
    emoji: "🏥",
    description: "AI tools for healthcare, wellness, medical assistance, and health monitoring",
    subcategories: [
      // Core health categories
      "Health & Wellness",
      "Health & Wellness Tools",
      "Healthcare Professionals",
      "Health And Wellness",
      "Health And Wellness Tools",
      "AI Healthcare Tools",
      // Additional health and wellness categories from our database
      "Healthcare",
      "Medical Tools",
      "Medical AI",
      "Health Tools",
      "Wellness Tools",
      "Medical Assistant",
      "Health Assistant",
      "Medical Care",
      "Healthcare AI",
      "Health AI",
      "Medical Technology",
      "Health Technology",
      "Clinical Tools",
      "Medical Diagnosis",
      "Health Diagnosis",
      "Medical Support",
      "Health Support",
      "Medical Analysis",
      "Health Analysis",
      "Medical Research",
      "Health Research",
      "Medical Information",
      "Health Information",
      "Medical Data",
      "Health Data",
      "Medical Records",
      "Health Records",
      "Medical Monitoring",
      "Health Monitoring",
      "Medical Tracking",
      "Health Tracking",
      "Medical Management",
      "Health Management",
      "Medical Planning",
      "Health Planning",
      "Medical Education",
      "Health Education",
      "Medical Training",
      "Health Training",
      "Medical Learning",
      "Health Learning",
      "Medical Knowledge",
      "Health Knowledge",
      "Medical Advice",
      "Health Advice",
      "Medical Guidance",
      "Health Guidance",
      "Medical Consultation",
      "Health Consultation",
      "Medical Assessment",
      "Health Assessment",
      "Medical Evaluation",
      "Health Evaluation",
      "Medical Screening",
      "Health Screening",
      "Medical Testing",
      "Health Testing",
      "Medical Examination",
      "Health Examination",
      "Medical Check-up",
      "Health Check-up",
      "Medical Prevention",
      "Health Prevention",
      "Medical Wellness",
      "Health Wellness",
      "Mental Health",
      "Mental Wellness",
      "Psychology",
      "Therapy",
      "Counseling",
      "Psychiatry",
      "Behavioral Health",
      "Emotional Health",
      "Stress Management",
      "Anxiety Management",
      "Depression Support",
      "Mindfulness",
      "Meditation",
      "Self-Care",
      "Wellness Coaching",
      "Health Coaching",
      "Fitness",
      "Exercise",
      "Physical Health",
      "Nutrition",
      "Diet",
      "Weight Management",
      "Sleep Health",
      "Sleep Management",
      "Pain Management",
      "Chronic Care",
      "Elderly Care",
      "Senior Health",
      "Pediatric Care",
      "Child Health",
      "Women's Health",
      "Men's Health",
      "Reproductive Health",
      "Dental Health",
      "Oral Health",
      "Eye Health",
      "Vision Care",
      "Hearing Health",
      "Audiology",
      "Dermatology",
      "Skin Care",
      "Cardiology",
      "Heart Health",
      "Neurology",
      "Brain Health",
      "Oncology",
      "Cancer Care",
      "Diabetes Care",
      "Diabetes Management",
      "Blood Pressure",
      "Hypertension",
      "Cholesterol",
      "Medical Devices",
      "Health Devices",
      "Wearable Health",
      "Health Sensors",
      "Telemedicine",
      "Remote Care",
      "Virtual Health",
      "Digital Health",
      "E-Health",
      "mHealth",
      "Health Apps",
      "Medical Apps",
      "Health Platforms",
      "Medical Platforms",
      "Health Software",
      "Medical Software",
      "Health Systems",
      "Medical Systems",
      "Electronic Health Records",
      "EHR",
      "Health Analytics",
      "Medical Analytics",
      "Health Insights",
      "Medical Insights",
      "Health Predictions",
      "Medical Predictions",
      "Health Risk Assessment",
      "Medical Risk Assessment",
      "Health Outcomes",
      "Medical Outcomes",
      "Patient Care",
      "Patient Management",
      "Patient Monitoring",
      "Patient Support",
      "Clinical Decision Support",
      "Medical Decision Support",
      "Evidence-Based Medicine",
      "Precision Medicine",
      "Personalized Medicine",
      "Healthcare Quality",
      "Medical Quality",
      "Healthcare Safety",
      "Medical Safety",
      "Healthcare Compliance",
      "Medical Compliance",
      "Healthcare Standards",
      "Medical Standards",
      "Healthcare Protocols",
      "Medical Protocols",
      "Healthcare Guidelines",
      "Medical Guidelines",
      "Healthcare Best Practices",
      "Medical Best Practices"
    ]
  },
  {
    name: "LEGAL & PROFESSIONAL SERVICES",
    emoji: "⚖️", 
    description: "AI tools for legal assistance, professional services, and compliance management",
    subcategories: [
      "Legal Professionals",
      "Professional Services",
      "Personal Services",
      "Resume & Career Tools",
      "Resume And Career Tools",
      "AI Legal Tools"
    ]
  }
];
