
import { MainCategory } from "./types";

export const serviceCategories: MainCategory[] = [
  {
    name: "EDUCATION & LEARNING",
    emoji: "🎓",
    description: "AI-powered educational tools, learning platforms, and knowledge management systems",
    subcategories: [
      // Core education categories
      "Education & Learning",
      "Learning & Education",
      "Learning Platforms",
      "Research & Learning",
      "Education And Learning",
      "Learning And Education",
      "Research And Learning",
      "AI Education Tools",
      "AI Research Tools",
      // Additional education categories from our database
      "Educational Tools",
      "Learning Tools",
      "Study Tools",
      "Academic Tools",
      "Course Creation",
      "Course Development",
      "Learning Management",
      "Educational Technology",
      "E-Learning",
      "Online Learning",
      "Distance Learning",
      "Educational Content",
      "Learning Content",
      "Educational Resources",
      "Learning Resources",
      "Study Resources",
      "Academic Resources",
      "Educational Platforms",
      "Learning Platforms",
      "Study Platforms",
      "Academic Platforms",
      "Educational Software",
      "Learning Software",
      "Study Software",
      "Academic Software",
      "Educational Systems",
      "Learning Systems",
      "Study Systems",
      "Academic Systems",
      "Educational Support",
      "Learning Support",
      "Study Support",
      "Academic Support",
      "Educational Assistance",
      "Learning Assistance",
      "Study Assistance",
      "Academic Assistance",
      "Educational Guidance",
      "Learning Guidance",
      "Study Guidance",
      "Academic Guidance",
      "Educational Coaching",
      "Learning Coaching",
      "Study Coaching",
      "Academic Coaching",
      "Educational Tutoring",
      "Learning Tutoring",
      "Study Tutoring",
      "Academic Tutoring",
      "Skill Development",
      "Skill Building",
      "Skill Enhancement",
      "Skill Training",
      "Professional Development",
      "Personal Development",
      "Career Development",
      "Knowledge Management",
      "Knowledge Sharing",
      "Knowledge Transfer",
      "Information Learning",
      "Data Learning",
      "Research Tools",
      "Study Planning",
      "Learning Planning",
      "Educational Planning",
      "Academic Planning",
      "Curriculum Planning",
      "Course Planning",
      "Lesson Planning",
      "Study Scheduling",
      "Learning Scheduling",
      "Educational Scheduling",
      "Academic Scheduling",
      "Progress Tracking",
      "Learning Progress",
      "Educational Progress",
      "Academic Progress",
      "Performance Tracking",
      "Learning Performance",
      "Educational Performance",
      "Academic Performance",
      "Assessment Tools",
      "Testing Tools",
      "Quiz Tools",
      "Evaluation Tools",
      "Grading Tools",
      "Feedback Tools",
      "Review Tools",
      "Analysis Tools",
      "Learning Analytics",
      "Educational Analytics",
      "Academic Analytics",
      "Student Analytics",
      "Learning Insights",
      "Educational Insights",
      "Academic Insights",
      "Student Insights",
      "Personalized Learning",
      "Adaptive Learning",
      "Customized Learning",
      "Individualized Learning",
      "Self-Paced Learning",
      "Interactive Learning",
      "Engaging Learning",
      "Immersive Learning",
      "Gamified Learning",
      "Social Learning",
      "Collaborative Learning",
      "Group Learning",
      "Team Learning",
      "Peer Learning",
      "Community Learning",
      "Mobile Learning",
      "Microlearning",
      "Bite-sized Learning",
      "Just-in-time Learning",
      "Continuous Learning",
      "Lifelong Learning",
      "Professional Learning",
      "Corporate Learning",
      "Enterprise Learning",
      "Business Learning",
      "Workplace Learning",
      "Training Tools",
      "Training Platforms",
      "Training Systems",
      "Training Software",
      "Training Programs",
      "Training Materials",
      "Training Resources",
      "Training Content",
      "Certification Tools",
      "Accreditation Tools",
      "Credentialing Tools",
      "Badge Systems",
      "Achievement Systems",
      "Reward Systems",
      "Recognition Systems",
      "Motivation Tools",
      "Engagement Tools",
      "Retention Tools",
      "Completion Tools"
    ]
  },
  {
    name: "HEALTH & WELLNESS",
    emoji: "🏥",
    description: "AI tools for healthcare, wellness, medical assistance, and health monitoring",
    subcategories: [
      "Health & Wellness",
      "Health & Wellness Tools",
      "Healthcare Professionals",
      "Health And Wellness",
      "Health And Wellness Tools",
      "AI Healthcare Tools"
    ]
  },
  {
    name: "LEGAL & PROFESSIONAL SERVICES",
    emoji: "⚖️", 
    description: "AI tools for legal assistance, professional services, and compliance management",
    subcategories: [
      "Legal Professionals",
      "Professional Services",
      "Personal Services",
      "Resume & Career Tools",
      "Resume And Career Tools",
      "AI Legal Tools"
    ]
  }
];
