
import { MainCategory } from "./types";

export const specializedCategories: MainCategory[] = [
  {
    name: "AI WEB TOOLS ORIGINALS",
    emoji: "🌟",
    description: "Exclusive AI tools and GPTs created by AI Web Tools company",
    subcategories: [
      "AI Web Tools GPTs",
      "Featured AI Web Tools",
      "Priority AI Web Tools",
      "Specialized AI Web Tools"
    ]
  },
  {
    name: "HISTORICAL & TIME-BASED AI TOOLS",
    emoji: "🕰️",
    description: "Tools for exploring history, time travel simulations, and historical analysis",
    subcategories: [
      "Time & History",
      "Historical & Cultural",
      "Time Travel Tools",
      "Historical Simulation"
    ]
  },
  {
    name: "Industry Specific AI TOOLS",
    emoji: "🏭",
    description: "AI tools designed for specific industries and professions - from healthcare to archaeology, cooking to graphic design",
    subcategories: [
      "Health, Wellness & Personal Lifestyle",
      "Health & Wellness",
      "Personal Services",
      "Lifestyle Tools",
      "Wellness & Fitness",
      "Healthcare Professionals",
      "Medical AI Tools",
      "Health And Wellness Tools",
      "Professional Services",
      "Legal Professionals",
      "Emergency Services",
      "Creative Services",
      "Education & Learning",
      "Education & Research Tools",
      "Educational & Research",
      "Industry-Specific Solutions",
      "Specialized Tools",
      "Specialized & Niche",
      "Specialized Niche Tools",
      "Specialized AI Tools",
      "Art & Collectibles",
      "Game Design & Development",
      "Financial & Trading Tools",
      "Finance & Trading",
      "Legal & Compliance",
      "Robotics Companies",
      "Technical & Utility Tools",
      "Food & Hospitality",
      "Culinary Arts",
      "Graphic Design",
      "Architecture",
      "Engineering",
      "Agriculture",
      "Real Estate",
      "Automotive",
      "Aviation",
      "Maritime",
      "Construction",
      "Mining",
      "Energy",
      "Environmental",
      "Sports",
      "Fashion",
      "Beauty",
      "Photography",
      "Journalism",
      "Broadcasting",
      "Publishing",
      "Library Science",
      "Museums",
      "Archaeology",
      "Anthropology",
      "Psychology",
      "Sociology",
      "Political Science",
      "Economics",
      "Statistics",
      "Research",
      "Scientific Research",
      "Laboratory",
      "Pharmaceutical",
      "Biotechnology",
      "Veterinary",
      "Dental",
      "Nursing",
      "Therapy",
      "Fitness",
      "Nutrition",
      "Mental Health",
      "Social Work",
      "Public Safety",
      "Security",
      "Military",
      "Government",
      "Non-profit",
      "Religious",
      "Spiritual",
      "Philosophy"
    ]
  },
  {
    name: "ROBOTICS & HARDWARE",
    emoji: "🤖",
    description: "Robotics companies, hardware tools, and IoT platforms",
    subcategories: [
      "Robotics Companies",
      "Hardware Tools",
      "IoT Platforms",
      "Smart Devices"
    ]
  }
];
