
import { Tool } from "@/types/tools";
import { 
  Scissors,
  PaintBucket,
  Target,
  Globe,
  Zap,
  Edit3,
  Sparkles,
  Bot,
  Video,
  Palette
} from "lucide-react";

export const backgroundAndObjectTools: Tool[] = [
  {
    icon: Target,
    title: "AI or Not",
    description: "Innovative tool designed to address the growing concern of AI-generated images being mistaken for human-created ones. Advanced detection capabilities determine whether images were generated by AI models like Stable Diffusion, MidJourney, DALL-E, or GAN.",
    emoji: "🎯",
    color: "from-purple-500 to-blue-600",
    directUrl: "https://www.aiornot.com/",
    tags: ["AI detection", "image authenticity", "Stable Diffusion", "MidJourney", "DALL-E", "Chrome extension"],
    category: "Image Generation Platforms",
    rating: 4.6,
    totalVotes: 3456
  },
  {
    icon: PaintBucket,
    title: "AutoDraw",
    description: "Free, web-based drawing tool from Google Creative Lab that uses machine learning to help users create high-quality drawings quickly and easily. Works on any device and turns doodles into good drawings with AI assistance.",
    emoji: "✏️",
    color: "from-blue-500 to-green-600",
    directUrl: "https://www.autodraw.com/",
    tags: ["Google Creative Lab", "machine learning", "doodle improvement", "any device", "free tool", "drawing assistance"],
    category: "Image Generation Platforms",
    rating: 4.1,
    totalVotes: 2876
  },
  {
    icon: Globe,
    title: "Background.lol",
    description: "Online platform that offers a quick and easy way to generate stunning AI cover images at no cost. User-friendly tool leverages artificial intelligence to create eye-catching cover images for various purposes.",
    emoji: "🖼️",
    color: "from-cyan-500 to-blue-600",
    directUrl: "https://www.background.lol/",
    tags: ["free cover images", "AI-powered", "social media", "presentations", "quick generation", "eye-catching"],
    category: "Image Generation Platforms",
    rating: 4.0,
    totalVotes: 1987
  },
  {
    icon: Zap,
    title: "Craiyon",
    description: "Ultimate AI image generator specializing in the creation of clean text icons, loading icons, and free-form drawings. Versatile styles and customizable options make it effortless to generate stunning AI art tailored for specific categories.",
    emoji: "🖍️",
    color: "from-rainbow-500 to-purple-600",
    directUrl: "https://www.craiyon.com/",
    tags: ["text icons", "loading icons", "free-form drawings", "versatile styles", "customizable", "stunning AI art"],
    category: "Image Generation Platforms",
    rating: 4.1,
    totalVotes: 2456
  },
  {
    icon: Scissors,
    title: "Cutout.pro",
    description: "AI-powered visual design platform catering to clean text icons, loading icons, and free-form drawings. Harnesses artificial intelligence and computer vision to offer diverse products for individual users and businesses with API integration.",
    emoji: "✂️",
    color: "from-blue-500 to-purple-600",
    directUrl: "https://www.cutout.pro/?vsource=cutout_share-406567850369093",
    tags: ["25k+ businesses", "background removal", "photo enhancer", "API integration", "visual design", "computer vision"],
    category: "Image Generation Platforms",
    rating: 4.4,
    totalVotes: 3234
  },
  {
    icon: Target,
    title: "Flair.ai",
    description: "Revolutionary AI design tool tailored for branded content creators. Drag product photos into Canvas, visually describe the scene, and AI fills the gaps to craft captivating branded content effortlessly with smart prompting.",
    emoji: "🎯",
    color: "from-orange-500 to-yellow-600",
    directUrl: "https://flair.ai/",
    tags: ["branded content", "product photos", "smart prompting", "branded content", "content creators", "AI-assisted design"],
    category: "Image Generation Platforms",
    rating: 4.5,
    totalVotes: 3789
  },
  {
    icon: Target,
    title: "Kartiv",
    description: "Revolutionary platform that empowers creatives to easily create stunning visuals using power of words. User-friendly interface without design knowledge, AI interprets descriptions and transforms them into captivating visuals.",
    emoji: "🎯",
    color: "from-orange-500 to-red-600",
    directUrl: "https://www.kartiv.com/",
    tags: ["words to visuals", "no design knowledge", "AI interpretation", "auto-resizing", "collaboration features", "design renaissance"],
    category: "Image Generation Platforms",
    rating: 4.4,
    totalVotes: 3456
  },
  {
    icon: Target,
    title: "Mage Space",
    description: "Versatile and user-friendly stable diffusion power image generator. AI-driven capabilities transform text into captivating art with over 60 AI models including text-to-image and text-to-GIF generators with 2048x2048 upscaling.",
    emoji: "🎯",
    color: "from-blue-500 to-purple-600",
    directUrl: "https://www.mage.space/",
    tags: ["60+ AI models", "text-to-GIF", "2048x2048 upscaling", "stable diffusion", "free online", "captivating art"],
    category: "Image Generation Platforms",
    rating: 4.5,
    totalVotes: 3789
  },
  {
    icon: Palette,
    title: "Khroma",
    description: "Cutting-edge design tool that helps you work with colors you love effortlessly. AI learns color preferences and generates limitless color palettes. Train neural network algorithm by selecting colors with various viewing options.",
    emoji: "🎨",
    color: "from-rainbow-500 to-purple-600",
    directUrl: "https://www.khroma.co/",
    tags: ["color preferences", "neural network", "limitless palettes", "typography", "gradients", "WCAG accessibility"],
    category: "Image Generation Platforms",
    rating: 4.5,
    totalVotes: 3789
  },
  {
    icon: Sparkles,
    title: "Let's Enhance Image Generator",
    description: "Cutting-edge AI tool that transforms text prompts into visually stunning artwork and digital assets. User-friendly prompt builder, upscaled to 2048x2048 pixels, suitable for prints and high-resolution screens with 16x enlargement.",
    emoji: "✨",
    color: "from-green-500 to-blue-600",
    directUrl: "https://letsenhance.io/ai-image-generation/",
    tags: ["text to artwork", "prompt builder", "2048x2048 pixels", "16x enlargement", "prints", "digital assets"],
    category: "Image Generation Platforms",
    rating: 4.7,
    totalVotes: 4567
  }
];
