
import { PenTool, Book, FileText, Edit, Mic, Headphones, Music, BookOpen } from "lucide-react";
import { Tool } from "@/types/tools";

export const contentCreationAndWritingTools: Tool[] = [
  {
    icon: PenTool,
    title: "WordHero",
    description: "AI-powered content creation tool loved by over 30,000 writers, marketers, and business owners. Generate original blog articles, social media content, emails, and more with over 80 writing tools.",
    emoji: "✍️",
    color: "from-blue-400 to-purple-500",
    directUrl: "https://wordhero.co/?via=aiwebtools",
    tags: ["content creation", "blog articles", "social media", "email marketing", "writing tools"],
    category: "Content Creation & Writing",
    rating: 4.6,
    totalVotes: 2890
  },
  {
    icon: Book,
    title: "BookWizard",
    description: "AI-powered platform that enables writing and publishing a book in just 60 minutes. Enter keywords or ideas, and BookWizard helps brainstorm, plan, and write your entire book preserving your unique voice.",
    emoji: "📚",
    color: "from-green-400 to-teal-500",
    directUrl: "https://bookwizard.co/?via=aiwebtools",
    tags: ["book writing", "publishing", "brainstorming", "unique voice", "quick creation"],
    category: "Content Creation & Writing",
    rating: 4.7,
    totalVotes: 2100
  },
  {
    icon: FileText,
    title: "StoriesForKids",
    description: "Transform real-life situations into engaging stories and illustrations within seconds. Combines fun and creativity for parents and educators to generate captivating narratives and visuals effortlessly.",
    emoji: "👶",
    color: "from-pink-400 to-purple-500",
    directUrl: "https://www.storiesforkids.ai/",
    tags: ["children stories", "illustrations", "education", "parenting", "creativity"],
    category: "Content Creation & Writing",
    rating: 4.5,
    totalVotes: 1890
  },
  {
    icon: Edit,
    title: "XDetector",
    description: "Free, multilingual AI content detection tool with over 99% accuracy in identifying AI-generated vs human-written text. Uses advanced techniques and Web3 encryption for data security.",
    emoji: "🔍",
    color: "from-red-400 to-orange-500",
    directUrl: "https://xdetector.ai/",
    tags: ["AI detection", "content verification", "academic integrity", "multilingual", "security"],
    category: "Content Detection & Analysis",
    rating: 4.8,
    totalVotes: 3200
  },
  {
    icon: FileText,
    title: "AiUndetect",
    description: "Pioneering AI anti-detection technology specializing in AI Humanizer algorithms. Help users effectively humanize AI text, making it indistinguishable from human-written content.",
    emoji: "🤖",
    color: "from-purple-400 to-pink-500",
    directUrl: "https://aiundetect.com/",
    tags: ["AI humanization", "undetectable text", "content rewriting", "AIGC", "text enhancement"],
    category: "Content Enhancement Tools",
    rating: 4.4,
    totalVotes: 2150
  },
  {
    icon: Edit,
    title: "AIhumanize",
    description: "Ensures AI text is rewritten into human text that cannot be detected by AI detectors. Humanizes AI text into high-quality human text with advanced rewriting algorithms.",
    emoji: "👤",
    color: "from-cyan-400 to-blue-500",
    directUrl: "https://aihumanize.io/",
    tags: ["AI humanization", "text rewriting", "undetectable", "high quality", "human-like"],
    category: "Content Enhancement Tools",
    rating: 4.3,
    totalVotes: 1950
  },
  {
    icon: FileText,
    title: "ZeroGPT",
    description: "AI content detection tool that identifies text likely generated by artificial intelligence. Analyzes linguistic patterns to provide percentage score of AI authorship for content verification.",
    emoji: "0️⃣",
    color: "from-gray-400 to-blue-500",
    directUrl: "https://www.zerogpt.com/",
    tags: ["AI detection", "content verification", "linguistic analysis", "plagiarism", "authenticity"],
    category: "Content Detection & Analysis",
    rating: 4.5,
    totalVotes: 2450
  },
  {
    icon: Mic,
    title: "Inpodcast AI",
    description: "Advanced AI tool for converting written documents into audio podcasts effortlessly. Transform articles, blog posts, or text-based content into high-quality spoken audio.",
    emoji: "🎙️",
    color: "from-orange-400 to-red-500",
    directUrl: "https://inpodcast.ai",
    tags: ["text to audio", "podcast creation", "content repurposing", "audio format", "accessibility"],
    category: "Audio & Content Tools",
    rating: 4.6,
    totalVotes: 1890
  },
  {
    icon: Headphones,
    title: "ElevenLabs TEXT Reader App",
    description: "Advanced AI tool for narrating text content including articles, PDFs, ePubs, and newsletters with highest quality voices. Available for Android and iOS devices.",
    emoji: "🎧",
    color: "from-purple-500 to-indigo-600",
    directUrl: "https://elevenlabs.io/text-reader",
    tags: ["text narration", "high quality voices", "mobile app", "content accessibility", "audio reading"],
    category: "Audio & Content Tools",
    rating: 4.8,
    totalVotes: 3100
  },
  {
    icon: Music,
    title: "Songgenerator.io",
    description: "Ultimate AI music creation tool transforming text into high-quality, royalty-free music. Features free online access, multiple styles, and rapid song creation in under a minute.",
    emoji: "🎵",
    color: "from-pink-400 to-purple-500",
    directUrl: "https://songgenerator.io/",
    tags: ["AI music", "text to music", "royalty-free", "multiple styles", "rapid creation"],
    category: "Audio & Music Tools",
    rating: 4.7,
    totalVotes: 2650
  },
  {
    icon: BookOpen,
    title: "FastRead",
    description: "AI-powered platform for publishing a complete book in less than 10 minutes. Input title, synopsis, and chapter structure, and AI generates content with custom chapter creation and images.",
    emoji: "⚡",
    color: "from-yellow-400 to-orange-500",
    directUrl: "https://fastread.io/?ref=aiwebtools",
    tags: ["rapid publishing", "book creation", "AI generation", "custom chapters", "quick content"],
    category: "Content Creation & Writing",
    rating: 4.5,
    totalVotes: 1780
  },
  {
    icon: BookOpen,
    title: "Story.com",
    description: "AI-driven platform for creating personalized children's books. Generate fully illustrated, customizable stories with real-time editing of characters, plotlines, and illustrations.",
    emoji: "📖",
    color: "from-green-400 to-blue-500",
    directUrl: "https://www.story.com",
    tags: ["children's books", "personalized stories", "illustrations", "real-time editing", "customizable"],
    category: "Content Creation & Writing",
    rating: 4.6,
    totalVotes: 2200
  }
];
