
// Tool abbreviations and fuzzy matching utilities
export const toolAbbreviations: Record<string, string[]> = {
  'ch': ['chatgpt', 'chat', 'character'],
  'cl': ['claude', 'clone', 'clean'],
  'cla': ['claude'],
  'gp': ['gpt', 'chatgpt'],
  'gpt': ['gpt', 'chatgpt'],
  'ai': ['ai', 'artificial'],
  'da': ['dalle', 'data'],
  'dall': ['dalle'],
  'mid': ['midjourney'],
  'sta': ['stable', 'start'],
  'gen': ['generator', 'generate'],
  'wr': ['write', 'writer'],
  'wri': ['write', 'writer', 'writing'],
  'des': ['design', 'designer'],
  'art': ['art', 'artist'],
  'mus': ['music', 'musician'],
  'vid': ['video'],
  'aud': ['audio'],
  'ima': ['image'],
  'pic': ['picture'],
  'pho': ['photo'],
  'bus': ['business'],
  'pro': ['productivity', 'professional'],
  'lea': ['learn', 'learning'],
  'edu': ['education', 'educational'],
  'hea': ['health', 'healthcare'],
  'fin': ['finance', 'financial'],
  'leg': ['legal'],
  'cod': ['code', 'coding'],
  'dev': ['development', 'developer'],
  'web': ['web', 'website'],
  'app': ['app', 'application'],
  'pla': ['platform'],
  'too': ['tool', 'tools'],
  'ass': ['assistant'],
  'hel': ['helper', 'help'],
  'gui': ['guide'],
  'sup': ['support'],
  'cre': ['create', 'creative', 'creator'],
  'mak': ['make', 'maker'],
  'bui': ['build', 'builder'],
  'edi': ['edit', 'editor'],
  'ana': ['analyze', 'analysis'],
  'res': ['research', 'resume'],
  'stu': ['study', 'student'],
  'tea': ['teach', 'teacher'],
  'tut': ['tutorial'],
  'cou': ['course'],
  'train': ['training', 'translate'],
  'med': ['medical', 'media'],
  'soc': ['social'],
  'mar': ['marketing'],
  'sal': ['sales'],
  'aut': ['automation', 'automotive'],
  'car': ['car', 'career'],
  'auto': ['automotive', 'automation'],
  'gam': ['game', 'gaming'],
  'ent': ['entertainment'],
  'fun': ['fun'],
  'spi': ['spiritual'],
  'rel': ['relaxation', 'religion'],
  'medi': ['meditation', 'medical'],
  'pea': ['peace'],
  'cal': ['calm', 'calendar'],
  'zen': ['zen'],
  'dre': ['dream'],
  'sle': ['sleep'],
  'ast': ['astrology'],
  'tar': ['tarot'],
  'ang': ['angel'],
  'can': ['cannabis'],
  'fis': ['fishing'],
  'cel': ['celebrity'],
  'ein': ['einstein'],
  'bin': ['binary'],
  'foo': ['food'],
  'qua': ['quality'],
  'his': ['history', 'historian'],
  'tim': ['time'],
  'travel': ['travel', 'training'],
  'dir': ['director'],
  'ske': ['sketch'],
  'sto': ['story', 'storyboard']
};

export const fuzzyMatches: Record<string, string[]> = {
  'chatgpt': ['chatgpt', 'chat gpt', 'gpt chat', 'gpt'],
  'claude': ['claude', 'claud'],
  'midjourney': ['midjourney', 'mid journey', 'midjorney'],
  'dalle': ['dalle', 'dall-e', 'dal-e', 'dali'],
  'stable': ['stable', 'stabl'],
  'openai': ['openai', 'open ai'],
  'anthropic': ['anthropic', 'antropic'],
  'google': ['google', 'googl'],
  'microsoft': ['microsoft', 'micro soft'],
  'generator': ['generator', 'generater', 'genrator'],
  'assistant': ['assistant', 'assitant', 'asistant'],
  'creative': ['creative', 'creativ', 'creatve'],
  'business': ['business', 'bussiness', 'busines'],
  'productivity': ['productivity', 'productivty', 'productiviy'],
  'education': ['education', 'educaton', 'educaion'],
  'development': ['development', 'developement', 'devlopment'],
  'professional': ['professional', 'proffesional', 'profesional']
};

export const acronymMatches: Record<string, string[]> = {
  'ai': ['artificial intelligence', 'ai'],
  'ml': ['machine learning'],
  'nlp': ['natural language processing'],
  'gpt': ['generative pre-trained transformer', 'gpt'],
  'ui': ['user interface'],
  'ux': ['user experience'],
  'seo': ['search engine optimization'],
  'api': ['application programming interface'],
  'sdk': ['software development kit'],
  'cms': ['content management system'],
  'crm': ['customer relationship management'],
  'erp': ['enterprise resource planning'],
  'hr': ['human resources'],
  'it': ['information technology'],
  'qa': ['quality assurance'],
  'cv': ['computer vision', 'curriculum vitae'],
  'ar': ['augmented reality'],
  'vr': ['virtual reality'],
  'iot': ['internet of things'],
  'saas': ['software as a service'],
  'b2b': ['business to business'],
  'b2c': ['business to consumer'],
  'roi': ['return on investment'],
  'kpi': ['key performance indicator']
};
