globalThis.localStorage = { getItem:()=>null, setItem:()=>{}, removeItem:()=>{}, clear:()=>{} };
globalThis.window = globalThis;
const { allTools } = await import('../src/data/toolsData.ts');
const { convertToolsToCSV } = await import('../src/utils/csvExport.ts');
const fs = await import('fs');
const csv = convertToolsToCSV(allTools);
const out = `/mnt/documents/AIWebTools-Complete-Directory-${allTools.length}-Tools.csv`;
fs.writeFileSync(out, csv);
console.log('Tools exported:', allTools.length);
console.log('File:', out);
